components:
  schemas:
    CustomImageType:
      properties:
        image:
          description: Base64 encoded image data
          example: iVBORw0KGgoAAAANSUhEUgAAAKwAAAAoCAYAAABjEB
          type: string
        imageName:
          description: Name of the image
          example: logo.jpg
          type: string
        modifyBy:
          description: User who created or modified the image
          example: john.doe@testuser.com
          type: string
        modifyTime:
          description: Recorded Epoch timestamp, when such modification took place
          example: "1681758000"
          format: date-time
          type: number
        modifyType:
          description: Last modification type if Created or Edited
          enum:
            - Created
            - Edited
          example: Created
          type: string
      type: object
info:
  contact: {}
  description: Custom Images API Specification
  title: Custom Images APIs
  version: 1.0.0
openapi: 3.0.0
paths:
  /notifications/customimages:
    get:
      description: This API returns the Custom Images that are added.
      operationId: CustomImagesController_getCustomImages
      parameters:
        - description: must be asc or desc
          in: query
          name: sortorder
          required: false
          schema:
            enum:
              - asc
              - desc
            type: string
        - in: query
          name: sortby
          required: false
          schema:
            type: string
        - description: limit should be between 1 and 100
          in: query
          name: limit
          required: false
          schema:
            type: number
        - description: offset as the page start
          in: query
          name: offset
          required: false
          schema:
            type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  count:
                    description: total number available in the system
                    example: "200"
                    type: integer
                  result:
                    items:
                      $ref: "#/components/schemas/CustomImageType"
                    type: array
                type: object
          description: Returns the result list of Custom Images along with total count
        "400":
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: Type of error
                    example: Bad Request
                    type: string
                  message:
                    description: Detailed error message
                    example: limit should be between 1 and 100
                    type: string
                type: object
          description: Returns the error
      summary: "Returns the paginated result of Custom Images. "
      tags:
        - custom-images
    post:
      description: This API creates the Custom Image record based on Image File binary.
      operationId: CustomImagesController_create
      requestBody:
        content:
          image/gif:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/jpeg:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/jpg:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/png:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomImageType"
          description: Returns the record that was created as part of image upload
        "404":
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: Type of error
                    example: Bad Request
                    type: string
                  message:
                    description: Detailed error message
                    example: image with the name already exists
                    type: string
                type: object
          description: Returns the error
      summary: "Create new Custom Image by posting an Image File binary object. "
      tags:
        - custom-images
    x-netskope-params:
      apiGroup: custom-images
      customerFacing: true
      nsPartner: true
      serviceConfig: ms-policy
      version: 2
  /notifications/customimages/{imagename}:
    delete:
      description: This API deletes the Custom Image record based on Image File Name.
      operationId: CustomImagesController_delete
      parameters:
        - in: path
          name: imagename
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  message:
                    description: Detailed error message
                    example: success
                    type: string
                type: object
          description: Returns the result of delete attempt
        "400":
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: Type of error
                    example: Bad Request
                    type: string
                  message:
                    description: Detailed error message
                    example: image with the name not found
                    type: string
                type: object
          description: Returns the error
      summary: "Deletes the Custom Image by a specific imagename "
      tags:
        - custom-images
    get:
      description: This API fetches the Custom Image record based on Image File Name.
      operationId: CustomImagesController_getSingleCustomImage
      parameters:
        - in: path
          name: imagename
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomImageType"
          description: Returns the record that was found with the given imageName
        "400":
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: Type of error
                    example: Bad Request
                    type: string
                  message:
                    description: Detailed error message
                    example: image not found
                    type: string
                type: object
          description: Returns the error
      summary: "Fetch the Custom Image by a specific imageName "
      tags:
        - custom-images
    put:
      description:
        This API updates the Custom Image record based on Image File Name
        and Image File binary.
      operationId: CustomImagesController_edit
      parameters:
        - in: path
          name: imagename
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/gif:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/jpeg:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/jpg:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
          image/png:
            schema:
              properties:
                file:
                  format: binary
                  type: string
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomImageType"
          description: Returns the record that was updated as part of image upload
        "400":
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: Type of error
                    example: Bad Request
                    type: string
                  message:
                    description: Detailed error message
                    example: image with the name not found
                    type: string
                type: object
          description: Returns the error
      summary: "Updates the Custom Image by a specific imageName "
      tags:
        - custom-images
    x-netskope-params:
      apiGroup: custom-images
      customerFacing: true
      nsPartner: true
      serviceConfig: ms-policy
      version: 2
servers: []
tags: []
