components:
  schemas:
    DeliverySettingsResponse:
      properties:
        cloudAppsDeliveryMethod:
          enum:
            - client
            - browser
          type: string
        notificationTimeout:
          description: Timeout in seconds.
          maximum: 600
          minimum: 60
          type: number
        webTrafficDeliveryMethod:
          enum:
            - client
            - browser
          type: string
      required:
        - cloudAppsDeliveryMethod
        - webTrafficDeliveryMethod
        - notificationTimeout
      type: object
    ErrorResponse:
      properties:
        message:
          type: string
      required:
        - message
      type: object
info:
  contact: {}
  description: Delivery settings API specification
  title: Delivery settings
  version: "1.0"
openapi: 3.0.0
paths:
  /notifications/user/deliverysettings:
    get:
      operationId: UserNotificationsDeliverySettingsController_readAllDeliverySettings
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeliverySettingsResponse"
          description: The record(s) have been successfully retrieved.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Reads user notification delivery settings.
      tags:
        - delivery-settings
    patch:
      operationId: UserNotificationsDeliverySettingsController_update
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeliverySettingsResponse"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeliverySettingsResponse"
          description: The record has been successfully updated.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Update user notification delivery settings.
      tags:
        - delivery-settings
    x-netskope-params:
      apiGroup: delivery-settings
      customerFacing: true
      nsPartner: true
      rateLimit:
        readRoutes:
          second: 4
        writeRoutes:
          second: 1
      serviceConfig: ms-rtp-shim
      version: 2
servers: []
tags:
  - name: delivery-settings
