components:
  schemas:
    ErrorResponse:
      properties:
        body:
          properties:
            errors:
              example:
                - We encountered a backend error. Please try again.
              items:
                type: string
              type: array
          type: object
        status:
          example: 400
          type: integer
      type: object
    FilterOptionsResponse:
      properties:
        data:
          description: Array of filter values
          items:
            properties:
              id:
                description: ID of the value
                example: key
                type: string
              name:
                description: Name of the value
                type: string
              parent:
                description: Parent value
                type: string
            type: object
          type: array
        next_cursor:
          description: Get records from this cursor. Empty if there are no more resources.
          type: string
      type: object
    InventoryFilterOptionsRequest:
      properties:
        cursor:
          default: 0
          description: Cursor from which the filter values are to be returned.
          type: string
        filter_key:
          description:
            API will fetch all possible values used in any policy of this
            field.
          enum:
            - app_suite
            - app_category
            - app_name
            - instance_name
            - region_id
            - resource_name
            - resource_id
            - resource_type
            - instance_group
            - instance_subgroup
            - instance_id
            - instance
            - tag
          type: string
        keyword:
          description: case-insensitive Keyword filter match for values.
          type: string
        limit:
          default: 50
          description: Limit of the filter values returned.
          type: integer
        timestamp:
          default: 0
          description:
            Timestamp for which filter values need to be fetched. 0 means
            latest timestamp
          type: integer
      type: object
info:
  description:
    APIs for fetching aggregated resource information and filters needed
    by Overview and Inventory dashboard
  title: SPM Inventory APIs
  version: v1
openapi: 3.0.3
paths:
  /spm/inventory/filters/getvalues:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InventoryFilterOptionsRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FilterOptionsResponse"
          description: Success response
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Error
        5XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Fetch all values of given filter_key referred in inventory.
    x-netskope-params:
      apiGroup: inventory_filters
      customerFacing: true
      nsBeta: true
      rateLimit:
        readRoutes:
          second: 10
        writeRoutes:
          second: 10
      serviceConfig: spm
      version: 2
servers:
  - url: https://spm-<tenant>-<app>.netskope.com/v1/spm
