components:
  schemas:
    ErrorResponse:
      description: https://netskope.atlassian.net/wiki/spaces/WUB/pages/2964751235/API+error+response
      properties:
        body:
          properties:
            errors:
              example:
                - error: We encountered a backend error. Please try again.
              items:
                properties:
                  error:
                    type: string
                required:
                  - error
                type: object
              type: array
          required:
            - errors
          type: object
        status:
          example: 400
          type: integer
      required:
        - body
        - status
      type: object
    ReportFilters:
      description:
        (Optional) Specific filters, if any, to be considered for the report,
        default is All.
      properties:
        app_suites:
          example: "[AzureAD, Salesforce]"
          items:
            type: string
          type: array
      type: object
    ReportSchedule:
      properties:
        day_of_month:
          type: string
        day_of_week:
          type: string
        filters:
          type: object
        frequency:
          type: string
        hour_of_day:
          type: string
        include_passed_findings:
          type: boolean
        mail_to:
          items:
            type: string
          type: array
        report_name:
          type: string
        report_schedule_id:
          type: string
        time_zone:
          type: string
      type: object
    ReportScheduleRequest:
      properties:
        day_of_month:
          description:
            Day of month on which report will be generated, this field
            is mandatory when frequency selected is monthly
          enum:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
            - "15"
            - "16"
            - "17"
            - "18"
            - "19"
            - "20"
            - "21"
            - "22"
            - "23"
            - "24"
            - "25"
            - "26"
            - "27"
            - "28"
          type: string
        day_of_week:
          description:
            Day of week on which report will be generated, this field is
            mandatory when frequency selected is weekly
          enum:
            - sunday
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
          type: string
        filters:
          $ref: "#/components/schemas/ReportFilters"
        frequency:
          description: Frequency of the report generation schedule
          enum:
            - now
            - daily
            - weekly
            - monthly
          example: daily
          type: string
        hour_of_day:
          description:
            Hour at which report will be generated. For any frequency except
            now, this field is mandatory.
          enum:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
            - "15"
            - "16"
            - "17"
            - "18"
            - "19"
            - "20"
            - "21"
            - "22"
            - "23"
          type: string
        include_passed_findings:
          default: false
          description:
            This will determine whether passed findings will be included
            in the report, only failed findings will be included by default.
          enum:
            - true
            - false
          type: boolean
        mail_to:
          example:
            - abc@example.com
          format: email
          items:
            type: string
          minItems: 1
          type: array
        report_name:
          description: Name of the report schedule and the generated report file name
          example: Compliance Report
          type: string
        time_zone:
          description: Time zone to be used for generating reports.
          enum:
            - Midway Island, Samoa(GMT-11:00)
            - Hawaii(GMT-10:00)
            - Alaska(GMT-09:00)
            - Pacific Time (US & Canada)(GMT-08:00)
            - Tijuana, Baja California(GMT-08:00)
            - Arizona(GMT-07:00)
            - Chihuahua, La Paz, Mazatlan(GMT-07:00)
            - Mountain Time (US & Canada)(GMT-07:00)
            - Central America(GMT-06:00)
            - Central Time (US & Canada)(GMT-06:00)
            - Guadalajara, Mexico City, Monterrey(GMT-06:00)
            - Saskatchewan(GMT-06:00)
            - Bogota, Lima, Quito, Rio Branco(GMT-05:00)
            - Eastern Time (US & Canada)(GMT-05:00)
            - Indiana (East)(GMT-05:00)
            - Atlantic Time (Canada)(GMT-04:00)
            - Caracas, La Paz(GMT-04:00)
            - Manaus(GMT-04:00)
            - Santiago(GMT-04:00)
            - Newfoundland(GMT-03:30)
            - Brasilia(GMT-03:00)
            - Buenos Aires, Georgetown(GMT-03:00)
            - Greenland(GMT-03:00)
            - Montevideo(GMT-03:00)
            - Cape Verde Is.(GMT-01:00)
            - Azores(GMT-01:00)
            - Casablanca, Monrovia, Reykjavik(GMT+00:00)
            - "Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London(GMT+00:00)"
            - Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna(GMT+01:00)
            - Belgrade, Bratislava, Budapest, Ljubljana, Prague(GMT+01:00)
            - Brussels, Copenhagen, Madrid, Paris(GMT+01:00)
            - Sarajevo, Skopje, Warsaw, Zagreb(GMT+01:00)
            - West Central Africa(GMT+01:00)
            - Amman(GMT+02:00)
            - Athens, Bucharest, Istanbul(GMT+02:00)
            - Beirut(GMT+02:00)
            - Cairo(GMT+02:00)
            - Harare, Pretoria(GMT+02:00)
            - Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius(GMT+02:00)
            - Jerusalem(GMT+02:00)
            - Minsk(GMT+02:00)
            - Windhoek(GMT+02:00)
            - Kuwait, Riyadh, Baghdad(GMT+03:00)
            - Moscow, St. Petersburg, Volgograd(GMT+03:00)
            - Nairobi(GMT+03:00)
            - Tbilisi(GMT+03:00)
            - Tehran(GMT+03:30)
            - Abu Dhabi, Muscat(GMT+04:00)
            - Baku(GMT+04:00)
            - Yerevan(GMT+04:00)
            - Kabul(GMT+04:30)
            - Yekaterinburg(GMT+05:00)
            - Islamabad, Karachi, Tashkent(GMT+05:00)
            - Sri Jayawardenapura(GMT+05:30)
            - Chennai, Kolkata, Mumbai, New Delhi(GMT+05:30)
            - Kathmandu(GMT+05:45)
            - Almaty, Novosibirsk(GMT+06:00)
            - Astana, Dhaka(GMT+06:00)
            - Yangon (Rangoon)(GMT+06:30)
            - Bangkok, Hanoi, Jakarta(GMT+07:00)
            - Krasnoyarsk(GMT+07:00)
            - Beijing, Chongqing, Hong Kong, Urumqi(GMT+08:00)
            - Kuala Lumpur, Singapore(GMT+08:00)
            - Irkutsk, Ulaan Bataar(GMT+08:00)
            - Perth(GMT+08:00)
            - Taipei(GMT+08:00)
            - Osaka, Sapporo, Tokyo(GMT+09:00)
            - Seoul(GMT+09:00)
            - Yakutsk(GMT+09:00)
            - Adelaide(GMT+09:30)
            - Darwin(GMT+09:30)
            - Brisbane(GMT+10:00)
            - Canberra, Melbourne, Sydney(GMT+10:00)
            - Hobart(GMT+10:00)
            - Guam, Port Moresby(GMT+10:00)
            - Vladivostok(GMT+10:00)
            - Magadan, Solomon Is., New Caledonia(GMT+11:00)
            - Auckland, Wellington(GMT+12:00)
            - Fiji, Kamchatka, Marshall Is.(GMT+12:00)
            - Nuku'alofa(GMT+13:00)
          example: Alaska(GMT-09:00)
          type: string
      required:
        - report_name
        - mail_to
        - frequency
        - time_zone
      type: object
    ReportSchedules:
      properties:
        nextOffset:
          type: integer
        reportSchedules:
          items:
            $ref: "#/components/schemas/ReportSchedule"
          type: array
      type: object
info:
  title: SPM Reports
  version: 1.0.0
openapi: 3.0.3
paths:
  /spm/report/schedules:
    get:
      description: Retrieves existing schedules
      parameters:
        - description: Minimum:0, Default:0
          in: query
          name: offset
          schema:
            description: The number of items to skip before collecting result
            type: integer
        - description: Minimum:1, Maximum:500, Default:50
          in: query
          name: limit
          schema:
            description: The numbers of items to return
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportSchedules"
          description: Retrieved schedules
        "204":
          description: No schedules found
        4XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Request is not valid
                status: 400
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request
        5XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Failed to process the response
                status: 500
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      summary: Retrieves existing schedules
      tags:
        - Reports Schedule
    post:
      description: Initiates and saves schedules for report generation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportScheduleRequest"
        description: Request payload for saving report schedules
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportSchedule"
          description: Report schedule created
        4XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Request is not valid
                status: 400
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request
        5XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Failed to process the response
                status: 500
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      summary: Initiates and saves schedules for report generation
      tags:
        - Reports Schedule
    x-netskope-params:
      apiGroup: reports
      customerFacing: true
      nsBeta: true
      rateLimit:
        readRoutes:
          second: 10
        writeRoutes:
          second: 10
      serviceConfig: spm
      version: 2
  /spm/report/schedules/{id}:
    delete:
      description: Deletes a scheduled report
      parameters:
        - description: report_schedule_id
          in: path
          name: id
          required: true
          schema:
            format: string
            minimum: 1
            type: string
      responses:
        "200":
          description: Schedule deleted
        4XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Request is not valid
                status: 400
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request
        5XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Failed to process the response
                status: 500
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      summary: Deletes a scheduled report
      tags:
        - Reports Schedule
    get:
      description: Retrieves a schedule
      parameters:
        - description: report_schedule_id
          in: path
          name: id
          required: true
          schema:
            format: string
            minimum: 1
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportSchedule"
          description: Retrieved schedule
        4XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Request is not valid
                status: 400
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request
        5XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Failed to process the response
                status: 500
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      summary: Retrieves a schedule
      tags:
        - Reports Schedule
    put:
      description: Updates a scheduled report configuration
      parameters:
        - description: report_schedule_id
          in: path
          name: id
          required: true
          schema:
            format: string
            minimum: 1
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportScheduleRequest"
        description: Request payload for updating report schedules
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportSchedule"
          description: Report schedule updated
        4XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Request is not valid
                status: 400
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request
        5XX:
          content:
            application/json:
              example:
                body:
                  errors:
                    - error: Failed to process the response
                status: 500
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error
      summary: Updates a scheduled report configuration
      tags:
        - Reports Schedule
    x-netskope-params:
      apiGroup: reports
      customerFacing: true
      nsBeta: true
      rateLimit:
        readRoutes:
          second: 10
        writeRoutes:
          second: 10
      serviceConfig: spm
      version: 2
servers:
  - url: https://cspm-<tenant>-<app>.netskope.com/v1/spm/results
tags:
  - description: API's for report scheduling
    name: Reports Schedule
