components:
  schemas:
    ErrorResponse:
      description: Error object returned by the APIs
      properties:
        body:
          properties:
            errors:
              items:
                example: '["We encountered a backend error. Please try again."]'
                type: string
              type: array
          type: object
        status:
          example: 400
          type: integer
      type: object
    FilterNumberValues:
      items:
        type: number
      type: array
    FilterStringValues:
      items:
        type: string
      type: array
    GetPostureScoresRequestBody:
      properties:
        filters:
          properties:
            app_names:
              $ref: "#/components/schemas/FilterStringValues"
            appsuite_names:
              $ref: "#/components/schemas/FilterStringValues"
            instance_names:
              $ref: "#/components/schemas/FilterStringValues"
            posture_confidence_level:
              $ref: "#/components/schemas/FilterStringValues"
          type: object
        timestamp:
          description:
            Timestamp, in UTC milliseconds, up to which the posture score
            is to be calculated.
          type: number
      type: object
    GetPostureScoresTrendRequestBody:
      properties:
        filters:
          properties:
            app_names:
              $ref: "#/components/schemas/FilterStringValues"
            appsuite_names:
              $ref: "#/components/schemas/FilterStringValues"
            instance_names:
              $ref: "#/components/schemas/FilterStringValues"
          type: object
        timestamp:
          description:
            Timestamp, in UTC milliseconds, up to which the posture score
            is to be calculated.
          type: number
      type: object
    PostureScoreData:
      properties:
        posture_confidence_index:
          description: SaaS Posture Confidence Index.
          example: 60
          type: integer
        posture_confidence_level:
          description: Posture Confidence Level based on confidence index value
          enum:
            - Excellent
            - High
            - Medium
            - Low
            - Poor
          example: Medium
          type: string
        posture_risk_score:
          description: SaaS Posture Risk Score.
          example: 40
          type: integer
      type: object
    PostureScoreDelta:
      description: information about the change in posture score
      properties:
        change_in_num:
          description: quantum of change in posture score
          example: "12"
          type: number
        notation:
          description: indicates whether the change is an absolute number of percentage
          enum:
            - percent
            - raw_value
          example: raw_value
          type: string
        trajectory:
          description: direction of change in posture score
          enum:
            - up
            - down
          example: up
          type: string
      type: object
    PostureScoreResponse:
      properties:
        app_suites:
          items:
            properties:
              instances:
                items:
                  properties:
                    apps:
                      items:
                        properties:
                          name:
                            description: Application Name
                            example: Defender
                            type: string
                          score:
                            $ref: "#/components/schemas/PostureScoreData"
                        type: object
                      type: array
                    name:
                      description: Instance Name
                      example: Microsoft365
                      type: string
                    score:
                      $ref: "#/components/schemas/PostureScoreData"
                  type: object
                type: array
              name:
                description: AppSuite Name
                example: Microsoft365
                type: string
              score:
                $ref: "#/components/schemas/PostureScoreData"
            type: object
          type: array
        score:
          $ref: "#/components/schemas/PostureScoreData"
      type: object
    PostureScoreTrendApp:
      properties:
        delta:
          $ref: "#/components/schemas/PostureScoreDelta"
        name:
          description: Name of the application
          example: Intune
          type: string
        samples:
          description: Samples of posture confidence index
          items:
            $ref: "#/components/schemas/PostureScoreTrendSample"
          type: array
      type: object
    PostureScoreTrendAppSuite:
      properties:
        delta:
          $ref: "#/components/schemas/PostureScoreDelta"
        instances:
          description: List of instances for this app-suite
          items:
            $ref: "#/components/schemas/PostureScoreTrendInstance"
          type: array
        name:
          description: Name of the app-suite
          example: AzureAD
          type: string
        samples:
          description: Samples of posture confidence index
          items:
            $ref: "#/components/schemas/PostureScoreTrendSample"
          type: array
      type: object
    PostureScoreTrendInstance:
      properties:
        apps:
          description: List of applications for this instance
          items:
            $ref: "#/components/schemas/PostureScoreTrendApp"
          type: array
        delta:
          $ref: "#/components/schemas/PostureScoreDelta"
        name:
          description: Name of the instance
          example: lz2d.onmicrosoft.com
          type: string
        samples:
          description: Samples of posture confidence index
          items:
            $ref: "#/components/schemas/PostureScoreTrendSample"
          type: array
      type: object
    PostureScoreTrendResponse:
      properties:
        appSuites:
          description: List of app-suites for this tenant
          items:
            $ref: "#/components/schemas/PostureScoreTrendAppSuite"
          type: array
        delta:
          $ref: "#/components/schemas/PostureScoreDelta"
        samples:
          description: Samples of posture confidence index at tenant level
          items:
            $ref: "#/components/schemas/PostureScoreTrendSample"
          type: array
      type: object
    PostureScoreTrendSample:
      properties:
        posture_confidence_index:
          description: Posture confidence index value at the specified timestamp
          example: 82
          type: number
        timestamp:
          description: Timestamp of the sample
          example: 1696924810
          type: number
      type: object
info:
  description:
    "This spec defines APIs for fetching the SaaS Application Posture Score.

    "
  title: SaaS Posture Score
  version: 1.0.0
openapi: 3.0.3
paths:
  /spm/results/getposturescores:
    post:
      operationId: GetPostureScores
      requestBody:
        content:
          application/json:
            example:
              filters:
                app_names:
                  - Defender
                appsuite_names:
                  - Microsoft365
                instance_names:
                  - microsoft365_account_id
              timestamp: 1696924810
            schema:
              $ref: "#/components/schemas/GetPostureScoresRequestBody"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostureScoreResponse"
          description: Success
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Error
        5XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Get the list of posture scores associated with SaaS application instances.
      tags:
        - SaaS Posture Score
    x-netskope-params:
      apiGroup: saas_posture_score
      customerFacing: true
      nsBeta: true
      rateLimit:
        readRoutes:
          second: 10
        writeRoutes:
          second: 10
      serviceConfig: spm
      version: 2
  /spm/results/getposturescores/trend:
    post:
      operationId: GetPostureScoresTrends
      requestBody:
        content:
          application/json:
            example:
              filters:
                app_names:
                  - Defender
                appsuite_names:
                  - Microsoft365
                instance_names:
                  - microsoft365_account_id
              timestamp: 1696924810
            schema:
              $ref: "#/components/schemas/GetPostureScoresTrendRequestBody"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostureScoreTrendResponse"
          description: Success
        4XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Error
        5XX:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
      summary: Get the trend of posture scores associated with SaaS application instances.
      tags:
        - SaaS Posture Score Trend
    x-netskope-params:
      apiGroup: saas_posture_score
      customerFacing: true
      nsBeta: true
      rateLimit:
        readRoutes:
          second: 10
        writeRoutes:
          second: 10
      serviceConfig: spm
      version: 2
servers:
  - url: https://spm-<tenant>-<app>.netskope.com
  - url: https://<spm-ingress-name>
tags:
  - name: SaaS Posture Score
