components:
  schemas:
    Error:
      properties:
        data:
          properties:
            message:
              description: user facing error message
              type: string
          required:
            - message
          type: object
        status:
          example: error
          type: string
      required:
        - status
      type: object
    MalwareFile:
      format: bytes
      type: string
info:
  description: Malware File Download APIs
  title: Malware File Download APIs
  version: 1.0.0
openapi: 3.0.3
paths:
  /incidents/tssincidents/{id}/malwarefile:
    get:
      description: Download Password Protected Zipped Malware File
      parameters:
        - description: incident_id attribute of Malware Incident
          in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              examples:
                File Access Denied by Remote Destination:
                  value:
                    data:
                      message: Malware File is inaccessible due to inadequate permission.
                    status: error
                Files Missing in Remote Destination:
                  value:
                    data:
                      message: Incident's Malware File not found in destination.
                    status: error
                Rate Limit from Remote Destination:
                  value:
                    data:
                      message:
                        Rate Limit quota exceeded for malware retention profile
                        destination.
                    status: error
                Transport Errors from Remote Destination:
                  value:
                    data:
                      message: Malware File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Error"
            application/zip:
              examples:
                Success:
                  value: byte string of password protected zipped malware file
              schema:
                $ref: "#/components/schemas/MalwareFile"
          description: Request Processed
        "400":
          content:
            application/json:
              examples:
                File was not Uploaded:
                  value:
                    data:
                      message: Incident's Malware File was not uploaded.
                    status: error
                Missing Incident in DB:
                  value:
                    data:
                      message: Malware incident not found.
                    status: error
                Remote Destination Deconfigured:
                  value:
                    data:
                      message:
                        Malware retention profile destination is deactivated
                        (or deleted).
                    status: error
              schema:
                $ref: "#/components/schemas/Error"
          description: Bad Request
        "500":
          content:
            application/json:
              examples:
                Internal DB Access Error:
                  value:
                    data:
                      message: Could not validate Incident.
                    status: error
                Non DB Internal Errors:
                  value:
                    data:
                      message: Malware File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Error"
          description: Internal Server Error
      summary: Download Password Protected Zipped Malware File
    x-netskope-params:
      apiGroup: ims_malware
      customerFacing: false
      serviceConfig: ims-restapisvc
      version: 2
