components:
  schemas:
    Error:
      properties:
        error:
          type: string
      required:
        - error
      type: object
    Forensics:
      properties:
        content:
          type: string
        meta:
          type: string
        preview_image:
          type: string
      required:
        - meta
        - content
      type: object
    OriginalFile:
      format: bytes
      type: string
    Response:
      properties:
        data:
          oneOf:
            - $ref: "#/components/schemas/Forensics"
            - $ref: "#/components/schemas/Error"
        status:
          enum:
            - success
            - error
          type: string
      type: object
    SubFile:
      format: bytes
      type: string
info:
  description: Forensics Download APIs
  title: Forensics Download APIs
  version: 1.0.0
openapi: 3.0.3
paths:
  /incidents/dlpincidents/{id}/forensics:
    get:
      description:
        Download Forensics (Metadata, Content and Preview Image) for the
        incident. The Metadata schema is [here](http://docs.netskope.com/RefDocs/REST-API/Forensics-Metadata-Schema.html).
      parameters:
        - description: dlp_incident_id attribute of Incident
          in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              examples:
                File Access Denied by Remote Destination:
                  value:
                    data:
                      error: Forensic File is inaccessible due to inadequate permission.
                    status: error
                Files Missing in Remote Destination:
                  value:
                    data:
                      error: Incident's Forensic File not found in destination.
                    status: error
                Rate Limit from Remote Destination:
                  value:
                    data:
                      error: Rate Limit quota exceeded for forensic profile destination.
                    status: error
                Success:
                  value:
                    data:
                      content: sample file content
                      meta: '{"meta":"data"}'
                      preview_image: base64encoded Image Thumbnail File
                    status: success
                Transport Errors from Remote Destination:
                  value:
                    data:
                      error: Forensic File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Request Processed
        "400":
          content:
            application/json:
              examples:
                Feature Not Configured for given Incident:
                  value:
                    data:
                      error: Forensics not configured.
                    status: error
                File was not Uploaded:
                  value:
                    data:
                      error: Incident's Forensic File was not uploaded.
                    status: error
                Missing Incident in DB:
                  value:
                    data:
                      error: Incident not found.
                    status: error
                Remote Destination Deconfigured:
                  value:
                    data:
                      error: Forensic profile destination is deactivated (or deleted).
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Bad Request
        "500":
          content:
            application/json:
              examples:
                Internal DB Access Error:
                  value:
                    data:
                      error: Could not validate Incident.
                    status: error
                Non DB Internal Errors:
                  value:
                    data:
                      error: Forensic File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Internal Server Error
      summary: Download Forensics
    x-netskope-params:
      apiGroup: ims_forensics
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
  /incidents/dlpincidents/{id}/originalfile:
    get:
      description: Download Zipped Original File
      parameters:
        - description: dlp_incident_id attribute of Incident
          in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              examples:
                File Access Denied by Remote Destination:
                  value:
                    data:
                      error: Original File is inaccessible due to inadequate permission.
                    status: error
                Files Missing in Remote Destination:
                  value:
                    data:
                      error: Incident's Original File not found in destination.
                    status: error
                Rate Limit from Remote Destination:
                  value:
                    data:
                      error: Rate Limit quota exceeded for forensic profile destination.
                    status: error
                Transport Errors from Remote Destination:
                  value:
                    data:
                      error: Original File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
            application/zip:
              examples:
                Success:
                  value: byte string of zipped original file
              schema:
                $ref: "#/components/schemas/OriginalFile"
          description: Request Processed
        "400":
          content:
            application/json:
              examples:
                Feature Not Configured for given Incident:
                  value:
                    data:
                      error: Original File Feature not configured.
                    status: error
                File was not Uploaded:
                  value:
                    data:
                      error: Incident's Original File was not uploaded.
                    status: error
                Missing Incident in DB:
                  value:
                    data:
                      error: Incident not found.
                    status: error
                Remote Destination Deconfigured:
                  value:
                    data:
                      error: Forensic profile destination is deactivated (or deleted).
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Bad Request
        "500":
          content:
            application/json:
              examples:
                Internal DB Access Error:
                  value:
                    data:
                      error: Could not validate Incident.
                    status: error
                Non DB Internal Errors:
                  value:
                    data:
                      error: Original File could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Internal Server Error
      summary: Download Zipped Original File
    x-netskope-params:
      apiGroup: ims_forensics
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
  /incidents/dlpincidents/{id}/subfile:
    get:
      description: Download Zipped SubFile
      parameters:
        - description: dlp_incident_id attribute of Incident
          in: path
          name: id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          content:
            application/json:
              examples:
                File Access Denied by Remote Destination:
                  value:
                    data:
                      error: SubFile is inaccessible due to inadequate permission.
                    status: error
                Files Missing in Remote Destination:
                  value:
                    data:
                      error: Incident's SubFile not found in destination.
                    status: error
                Rate Limit from Remote Destination:
                  value:
                    data:
                      error: Rate Limit quota exceeded for forensic profile destination.
                    status: error
                Transport Errors from Remote Destination:
                  value:
                    data:
                      error: SubFile could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
            application/zip:
              examples:
                Success:
                  value: byte string of zipped SubFile
              schema:
                $ref: "#/components/schemas/SubFile"
          description: Request Processed
        "400":
          content:
            application/json:
              examples:
                Feature Not Configured for given Incident:
                  value:
                    data:
                      error: Original File Feature not configured.
                    status: error
                File was not Uploaded:
                  value:
                    data:
                      error: Incident's SubFile was not uploaded.
                    status: error
                Missing Incident in DB:
                  value:
                    data:
                      error: Incident not found.
                    status: error
                No Associated SubFile:
                  value:
                    data:
                      error: Incident has no SubFile.
                    status: error
                Remote Destination Deconfigured:
                  value:
                    data:
                      error: Forensic profile destination is deactivated (or deleted).
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Bad Request
        "500":
          content:
            application/json:
              examples:
                Internal DB Access Error:
                  value:
                    data:
                      error: Could not validate Incident.
                    status: error
                Non DB Internal Errors:
                  value:
                    data:
                      error: SubFile could not be retrieved.
                    status: error
              schema:
                $ref: "#/components/schemas/Response"
          description: Internal Server Error
      summary: Download Zipped SubFile
    x-netskope-params:
      apiGroup: ims_forensics
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
