components:
  schemas:
    400Response:
      properties:
        message:
          type: string
      type: object
    incident_update_200_response_item:
      properties:
        ok:
          type: integer
        result:
          type: string
      type: object
    incident_update_500_response_item:
      properties:
        ok:
          type: integer
        result:
          type: string
      type: object
    incident_update_patch_request:
      properties:
        payload:
          items:
            properties:
              field:
                description:
                  Field that needs to be modified ["status", "assignee",
                  "severity"]
                example: status
                type: string
              new_value:
                description: The new value of the field to be applied
                example: in_progress
                type: string
              object_id:
                description: Incident object that needs to be modified
                example: incident_object_id
                type: string
              old_value:
                description: Old value of the field that is being changed
                example: new
                type: string
              user:
                description: User updating the incident
                example: user@domain.com
                type: string
            type: object
          type: array
      type: object
    incident_update_response_200:
      properties:
        result:
          items:
            $ref: "#/components/schemas/incident_update_200_response_item"
          type: array
      type: object
    incident_update_response_500:
      properties:
        result:
          items:
            $ref: "#/components/schemas/incident_update_500_response_item"
          type: array
      type: object
info:
  description:
    API provides the way to update the Incident object generated by Netskope
    DLP solutions
  title: Netskope Incident Update Endpoints
  version: ""
openapi: 3.0.0
paths:
  /incidents/update:
    patch:
      description:
        API gives the flexibility to update the incident attributes ["status",
        "assignee", "severity"] and also it supports bulk updates
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/incident_update_patch_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/incident_update_response_200"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400Response"
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/incident_update_response_500"
          description: Failed Operation
      summary: Update incident object attributes
    x-netskope-params:
      apiGroup: incident_update
      customerFacing: true
      rateLimit:
        readRoutes:
          minute: 10
          second: 1
        writeRoutes:
          minute: 10
          second: 1
      serviceConfig: queryservice
      version: 2
