components:
  schemas:
    notification:
      description: Notification to be sent for the enforcement.
      minProperties: 1
      properties:
        email:
          $ref: "#/components/schemas/notificationEmail"
      type: object
    notificationEmail:
      description: Email is a user configured notification sent by email.
      properties:
        emails:
          description: Misc recipients of the notification.
          items:
            type: string
          type: array
        fromUser:
          description: Sender of the notification.
          format: email
          type: string
        interval:
          description:
            Interval in minutes between notifications, -1 indicates that
            the notification is disabled, 0 indicates that the notification should
            be sent immediately.
          format: int64
          minimum: -1
          type: integer
        templates:
          description: Message template IDs for recipient types.
          items:
            $ref: "#/components/schemas/notificationTemplate"
          type: array
        toUsers:
          description: Recipient types.
          items:
            enum:
              - owner
              - admin
              - manager
              - collaborators
              - emails
              - custodian
            type: string
          type: array
      required:
        - interval
        - templates
      type: object
    notificationTemplate:
      description: Template is a map of recipient type and notification template ID.
      properties:
        admin:
          description:
            The ID of notification template which will be used to send
            to the tenant admin of the entity.
          format: int64
          type: integer
        collaborators:
          description:
            The ID of notification template which will be used to send
            to the collaborators of the entity.
          format: int64
          type: integer
        custodian:
          description:
            The ID of notification template which will be used to send
            to misc custodian recipients.
          format: int64
          type: integer
        emails:
          description:
            The ID of notification template which will be used to send
            to misc email recipients.
          format: int64
          type: integer
        manager:
          description:
            The ID of notification template which will be used to send
            to the manager of owner of the entity.
          format: int64
          type: integer
        owner:
          description:
            The ID of notification template which will be used to send
            to the owner of the entity.
          format: int64
          type: integer
      type: object
info:
  description: ""
  title: ""
  version: ""
openapi: 3.0.0
paths: {}
