components:
  schemas:
    BadRequest:
      properties:
        err:
          description: A human-readable error message
          type: string
        error_code:
          description: HTTP error code
          example: 400
          type: integer
        reason:
          description: Reason code
          example: Bad Request
          type: string
      type: object
    ErrorResponse:
      properties:
        err:
          description: A human-readable error message
          type: string
        error_code:
          description: HTTP error code
          example: 429
          type: integer
        reason:
          description: Reason code
          example: Too Many Requests
          type: string
      type: object
    IncidentEventResponse:
      properties:
        result:
          items:
            type: object
          type: array
        status:
          properties:
            count:
              description: Number of results returned
              type: integer
            execution:
              description: Execution status
              enum:
                - Success
                - Failed
              type: string
            message:
              example: Successfully executed
              type: string
            status_code:
              description: HTTP status code
              example: 200
              type: integer
          type: object
      type: object
info:
  description: ""
  title: ""
  version: 1.0.0
openapi: 3.0.0
paths:
  /events/datasearch/incident:
    get:
      description:
        "Get incident events generated and collected by Clickhouse. User
        can filter by various parameters: starttime, endtime or query parameters."
      parameters:
        - description: Query timeout, in seconds
          in: query
          name: timeout
          required: true
          schema:
            default: 180
            type: integer
        - description: JQL query to filter the alerts by
          in: query
          name: query
          schema:
            type: string
        - description: Start time, in Unix timestamp, of the desired alerts
          in: query
          name: starttime
          schema:
            type: integer
        - description: End time, in Unix timestamp, of the desired alerts
          in: query
          name: endtime
          schema:
            type: integer
        - description: Query timeout
          in: query
          name: offset
          schema:
            type: integer
        - description: Number of results to limit the output by
          in: query
          name: limit
          schema:
            type: integer
        - description: Number of results to limit the sub-aggregations by
          in: query
          name: sublimit
          schema:
            type: integer
        - description: Fields to aggregate on
          in: query
          name: groupbys
          schema:
            items:
              type: string
            type: array
        - description: Secondary fields to aggregate on
          in: query
          name: subgroupbys
          schema:
            items:
              type: string
            type: array
        - description: Fields to sort the results by
          in: query
          name: orderbys
          schema:
            items:
              type: string
            type: array
        - description: For debugging purposes to show the SQL query that was run
          in: query
          name: explain
          schema:
            items:
              default: 1
              enum:
                - 0
                - 1
              type: integer
            type: array
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IncidentEventResponse"
          description: Successful Operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
          description: Bad Request
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Too Many Requests
      summary: Get incident events generated and collected by Clickhouse
    x-netskope-params:
      apiGroup: incident
      customerFacing: false
      nsPartner: true
      serviceConfig: queryservice
      version: 2
