components:
  schemas:
    transaction_events_token_200:
      description:
        "1.New customer authorized for transaction events, subscription\
        \ key and path are generated for the first time. \n\n2.Existing customer authorized\
        \ for transaction events, retrieving subscription key and path again."
      properties:
        ok:
          default: 1
          enum:
            - 0
            - 1
          type: integer
        result:
          properties:
            subscription:
              type: string
            subscription-key:
              type: string
          type: object
      type: object
    transaction_events_token_400:
      description:
        "1.Tenant ID is missing or not an interger. \n\n2.Regenerate parameter\
        \ value is invalid."
      properties:
        message:
          type: string
      type: object
    transaction_events_token_401:
      description:
        "Customer is not authorized to create/get subscription key and\
        \ path. \n\nThis is a licensed feature, please contact Netskope support to\
        \ purchase"
      properties:
        message:
          type: string
      type: object
    transaction_events_token_449:
      description:
        "1. Existing customer authorized for transaction events, subscription\
        \ key and path were already downloaded. \n\n2.Use regenerate=true option to\
        \ regenerate the subscription key. \n\n3.This is a one time step to onboard\
        \ the existing customer to the API. \n\n4.Please start using the new subscription\
        \ key as the existing key one has been invalidated."
      properties:
        message:
          type: string
      type: object
    transaction_events_token_500:
      description: API failed unexpectedly
      properties:
        message:
          type: string
      type: object
info:
  description: ""
  title: ""
  version: ""
openapi: 3.0.0
paths:
  /events/token/transaction_events:
    get:
      description:
        Get subscription key and path generated by Netskope to be used
        for subscribing to transaction events stored in PubSubLite. Subscription key
        response will be in encoded format by default. Use optional parameter decode=true
        to return response in decoded format.
      parameters:
        - description:
            "Do not use this parameter unless existing credentials have become\
            \ invalid as regenerate=true will invalidate the existing credentials. \n\
            \nNote: Regenerating subscription key will invalidate the existing key but\
            \ subscription path will not be updated so that clients can continue consuming\
            \ events where they left off."
          in: query
          name: regenerate
          required: false
          schema:
            default: "false"
            enum:
              - "true"
              - "false"
            type: string
        - description: Return subscription key response in decoded format.
          in: query
          name: decode
          required: false
          schema:
            default: "false"
            enum:
              - "true"
              - "false"
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction_events_token_200"
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction_events_token_400"
          description: Invalid request
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction_events_token_401"
          description:
            This is a licensed feature, please contact Netskope support
            to purchase
        "449":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction_events_token_449"
          description:
            "Subscription key was already downloaded by the customer. \n\
            \nUse regenerate=true to retrieve the new key."
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction_events_token_500"
          description: Internal server error
      summary: Retrieve subscription key and path for Netskope transaction events
    x-netskope-params:
      apiGroup: transaction
      customerFacing: true
      rateLimit:
        readRoutes:
          second: 1
        writeRoutes:
          second: 1
      serviceConfig: queryservice
      version: 2
