components:
  schemas:
    ErrorResponse:
      properties:
        message:
          type: string
      required:
        - message
      type: object
    HTTPHeader:
      properties:
        custom:
          default: false
          type: boolean
        matches:
          items:
            $ref: "#/components/schemas/MatchType"
          minItems: 1
          type: array
        name:
          type: string
      required:
        - name
        - matches
      type: object
    HttpHeaderProfileCreateRequest:
      anyOf:
        - properties:
            requestHeaders:
              items:
                $ref: "#/components/schemas/HTTPHeader"
              type: array
          type: object
        - properties:
            responseHeaders:
              items:
                $ref: "#/components/schemas/HTTPHeader"
              type: array
          type: object
      properties:
        name:
          type: string
      required:
        - name
      type: object
    HttpHeaderProfileDeleteResponse:
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
      type: object
    HttpHeaderProfileResponse:
      properties:
        id:
          type: string
        name:
          type: string
        requestHeaders:
          items:
            $ref: "#/components/schemas/HTTPHeader"
          type: array
        responseHeaders:
          items:
            $ref: "#/components/schemas/HTTPHeader"
          type: array
      type: object
    MatchType:
      properties:
        operator:
          enum:
            - gt
            - gte
            - lt
            - lte
            - in
            - eq
            - neq
          type: string
        type:
          enum:
            - string
            - regex
            - int
          type: string
        values:
          description:
            For "type" = "int", only 1 value is allowed in values[] array,
            except if the "operator" = "in", in that case max 2 values are allowed
            [min, max]
          items:
            type: string
          type: array
      required:
        - type
        - values
      type: object
info:
  contact: {}
  description: Http Header Profile API specification
  title: Http Header Profile APIs
  version: "1.0"
openapi: 3.0.0
paths:
  /profiles/httpheaders:
    get:
      parameters:
        - example: id, name, requestHeaders, responseHeaders
          in: query
          name: fields
          required: false
          schema:
            items:
              type: string
            type: array
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/HttpHeaderProfileResponse"
                type: array
          description: The record(s) have been successfully retrieved.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Get all http header profiles
      tags:
        - http-header-profiles
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HttpHeaderProfileCreateRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpHeaderProfileResponse"
          description: The record has been successfully created.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Create one http header profile
      tags:
        - http-header-profiles
    x-netskope-params:
      apiGroup: http-header-profiles
      customerFacing: true
      nsPartner: true
      rateLimit:
        readRoutes:
          second: 4
        writeRoutes:
          second: 1
      serviceConfig: ms-rtp-shim
      version: 2
  /profiles/httpheaders/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpHeaderProfileDeleteResponse"
          description: The record has been successfully deleted.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not found.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Delete one http header profile
      tags:
        - http-header-profiles
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpHeaderProfileResponse"
          description: The record has been successfully retrieved.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not found.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Get one http header profile
      tags:
        - http-header-profiles
    patch:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HttpHeaderProfileCreateRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpHeaderProfileResponse"
          description: The record has been successfully updated.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad request.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not found.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal server error.
      summary: Update one http header profile
      tags:
        - http-header-profiles
    x-netskope-params:
      apiGroup: http-header-profiles
      customerFacing: true
      nsPartner: true
      rateLimit:
        readRoutes:
          second: 4
        writeRoutes:
          second: 1
      serviceConfig: ms-rtp-shim
      version: 2
servers: []
tags:
  - name: http-header-profiles
