components:
  schemas:
    SiteIdErrorResponse:
      properties:
        message:
          description: user facing error message
          type: string
      required:
        - message
      type: object
    SiteIdResponse:
      properties:
        data:
          oneOf:
            - $ref: "#/components/schemas/SiteIdSuccessResponse"
            - $ref: "#/components/schemas/SiteIdErrorResponse"
        status:
          enum:
            - success
            - error
          type: string
      required:
        - status
        - data
      type: object
    SiteIdSuccessResponse:
      properties:
        siteid:
          description: site id
          type: string
      required:
        - siteid
      type: object
    ValidationResponse:
      properties:
        data:
          properties:
            message:
              description: user facing error message
              type: string
          type: object
        status:
          example: success | error
          type: string
      type: object
    container:
      properties:
        container:
          example: azure-container
          type: string
        storage_account:
          example: azure-storage-account
          type: string
      type: object
    emailId:
      properties:
        email_id:
          example: user@domain
          type: string
      type: object
    siteUrl:
      properties:
        url:
          example: https://sample.sharepoint/sites/sample-site
          type: string
      type: object
info:
  description: Forensic & Malware Retention Profile Validation
  title: Forensic & Malware Retention Profile Validation
  version: 1.0.0
openapi: 3.0.3
paths:
  /profiles/forensic/azure/instances/{name}/validation:
    post:
      description: validate the azure storage account & container name
      parameters:
        - in: path
          name: name
          required: true
          schema:
            example: azure-instance
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/container"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Download Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during download blobs. Verify custom
                        roles assigned in Azure AD portal
                    status: error
                Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during container validation. Verify
                        custom roles assigned in Azure AD portal
                    status: error
                Invalid Container:
                  value:
                    data:
                      message: Storage account / Container doesn't exists
                    status: error
                RateLimits from Azure:
                  value:
                    data:
                      message: Rate Limit quota exceeded for azure instance - {instance-name}
                    status: error
                ServiceUnavailable from Azure:
                  value:
                    data:
                      message: Service unavailable for azure instance - {instance-name}
                    status: error
                Successful Response:
                  value:
                    data:
                      message: Validation successful
                    status: success
                Unauthorized from Azure:
                  value:
                    data:
                      message: Authentication failure in azure instance - {instance-name}
                    status: error
                Upload Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during upload blobs. Verify custom
                        roles assigned in Azure AD portal
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Azure Container Validation Successful
        "400":
          content:
            application/json:
              examples:
                Invalid Azure Instance:
                  value:
                    data:
                      message: Azure instance - {instance-name} doesn't exists
                    status: error
                Missing Input Params:
                  value:
                    data:
                      message: "Missing parameters: Azure Storage account, container"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Bad Input on the request
        "500":
          content:
            application/json:
              example:
                data:
                  message: Internal Server Error while processing
                status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Internal Server Error
      summary: validate the azure storage account & container name
    x-netskope-params:
      apiGroup: ims-profiles
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
  /profiles/forensic/box/instances/{name}/validation:
    post:
      description: validate the Box user email id
      parameters:
        - in: path
          name: name
          required: true
          schema:
            example: box-instance
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/emailId"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Inactive user Email ID:
                  value:
                    data:
                      message: Email ID - {emailID} is not an active user
                    status: error
                Invalid Email ID:
                  value:
                    data:
                      message: Email ID - {emailID} doesn't exists
                    status: error
                RateLimits from Box:
                  value:
                    data:
                      message: Rate Limit quota exceeded for box instance - {instance-name}
                    status: error
                ServiceUnavailable from Box:
                  value:
                    data:
                      message: Service unavailable for box instance - {instance-name}
                    status: error
                Successful Response:
                  value:
                    data:
                      message: Validation successful
                    status: success
                Unauthorized from Box:
                  value:
                    data:
                      message: Authentication failure in box instance - {instance-name}
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Box user email ID validation is Successful
        "400":
          content:
            application/json:
              examples:
                Invalid Box Instance:
                  value:
                    data:
                      message: Box instance - {instance-name} doesn't exists
                    status: error
                Missing Email ID:
                  value:
                    data:
                      message: Email ID is missing
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Bad Input on the request
        "500":
          content:
            application/json:
              example:
                data:
                  message: Internal Server Error while processing
                status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Internal Server Error
      summary: validate the box user's email id
    x-netskope-params:
      apiGroup: ims-profiles
      customerFacing: false
      serviceConfig: ims-restapisvc
      version: 2
  /profiles/forensic/gdrive/instances/{name}/validation:
    post:
      description: validate the google drive admin email id
      parameters:
        - in: path
          name: name
          required: true
          schema:
            example: gdrive-instance
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/emailId"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Inactive user Email ID:
                  value:
                    data:
                      message: Email ID - {emailID} is not an active user
                    status: error
                Invalid Email ID:
                  value:
                    data:
                      message: Email ID - {emailID} doesn't exists
                    status: error
                RateLimits from Google Drive:
                  value:
                    data:
                      message: Rate Limit quota exceeded for gdrive instance - {instance-name}
                    status: error
                ServiceUnavailable from Google Drive:
                  value:
                    data:
                      message: Service unavailable for gdrive instance - {instance-name}
                    status: error
                Successful Response:
                  value:
                    data:
                      message: Validation successful
                    status: success
                Unauthorized from Google Drive:
                  value:
                    data:
                      message: Authentication failure in gdrive instance - {instance-name}
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Google Drive admin email ID validation is Successful
        "400":
          content:
            application/json:
              examples:
                Invalid Google Drive Instance:
                  value:
                    data:
                      message: Gdrive instance - {instance-name} doesn't exists
                    status: error
                Missing Email ID:
                  value:
                    data:
                      message: Email ID is missing
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Bad Input on the request
        "500":
          content:
            application/json:
              example:
                data:
                  message: Internal Server Error while processing
                status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Internal Server Error
      summary: validate the google drive admin email id
    x-netskope-params:
      apiGroup: ims-profiles
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
  /profiles/forensic/sharepoint/instances/{name}/getsiteid:
    post:
      description: retrieve the siteid for the given sharepoint site url
      parameters:
        - in: path
          name: name
          required: true
          schema:
            example: sharepoint-instance
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/siteUrl"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Invalid Sharepoint URL:
                  value:
                    data:
                      message: Sharepoint url - {siteUrl} doesn't exists
                    status: error
                RateLimits from Sharepoint:
                  value:
                    data:
                      message:
                        Rate Limit quota exceeded for sharepoint instance -
                        {instance-name}
                    status: error
                ServiceUnavailable from Sharepoint:
                  value:
                    data:
                      message: Service unavailable for sharepoint instance - {instance-name}
                    status: error
                Successful Response:
                  value:
                    data:
                      siteid: sharepoint-site-subsite-id
                    status: success
                Unauthorized from Sharepoint:
                  value:
                    data:
                      message: Authentication failure in sharepoint instance - {instance-name}
                    status: error
              schema:
                $ref: "#/components/schemas/SiteIdResponse"
          description: Sharepoint URL Validation Successful
        "400":
          content:
            application/json:
              examples:
                Invalid Sharepoint Instance:
                  value:
                    data:
                      message: Sharepoint instance - {instance-name} doesn't exists
                    status: error
                Missing Sharepoint URL:
                  value:
                    data:
                      message: Sharepoint url is missing
                    status: error
              schema:
                $ref: "#/components/schemas/SiteIdResponse"
          description: Bad Input on the request
        "500":
          content:
            application/json:
              example:
                data:
                  message: Internal Server Error while processing
                status: error
              schema:
                $ref: "#/components/schemas/SiteIdResponse"
          description: Internal Server Error
      summary: retrieve the siteid for the given sharepoint site url
    x-netskope-params:
      apiGroup: ims-profiles
      customerFacing: true
      serviceConfig: ims-restapisvc
      version: 2
  /profiles/malware/azure/instances/{name}/validation:
    post:
      description: validate the azure storage account & container name
      parameters:
        - in: path
          name: name
          required: true
          schema:
            example: azure-instance
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/container"
        required: true
      responses:
        "200":
          content:
            application/json:
              examples:
                Download Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during download blobs. Verify custom
                        roles assigned in Azure AD portal
                    status: error
                Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during container validation. Verify
                        custom roles assigned in Azure AD portal
                    status: error
                Invalid Container:
                  value:
                    data:
                      message: Storage account / Container doesn't exists
                    status: error
                RateLimits from Azure:
                  value:
                    data:
                      message: Rate Limit quota exceeded for azure instance - {instance-name}
                    status: error
                ServiceUnavailable from Azure:
                  value:
                    data:
                      message: Service unavailable for azure instance - {instance-name}
                    status: error
                Successful Response:
                  value:
                    data:
                      message: Validation successful
                    status: success
                Unauthorized from Azure:
                  value:
                    data:
                      message: Authentication failure in azure instance - {instance-name}
                    status: error
                Upload Forbidden from Azure:
                  value:
                    data:
                      message:
                        Forbidden error during upload blobs. Verify custom
                        roles assigned in Azure AD portal
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Azure Container Validation Successful
        "400":
          content:
            application/json:
              examples:
                Invalid Azure Instance:
                  value:
                    data:
                      message: Azure instance - {instance-name} doesn't exists
                    status: error
                Missing Input Params:
                  value:
                    data:
                      message: "Missing parameters: Azure Storage account, container"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Bad Input on the request
        "500":
          content:
            application/json:
              example:
                data:
                  message: Internal Server Error while processing
                status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
          description: Internal Server Error
      summary: validate the azure storage account & container name
    x-netskope-params:
      apiGroup: ims-profiles
      customerFacing: false
      serviceConfig: ims-restapisvc
      version: 2
