components:
  schemas:
    private_apps_get_response:
      items:
        properties:
          data:
            properties:
              allow_unauthenticated_cors:
                type: boolean
              allow_uri_bypass:
                type: boolean
              uribypass_header_value:
                type: string
              bypass_uris:
                items:
                  type: string
                type: array
              app_id:
                format: int32
                type: integer
              app_name:
                type: string
              app_option:
                type: object
              clientless_access:
                type: boolean
              host:
                type: string
              is_user_portal_app:
                type: boolean
              protocols:
                items:
                  $ref: "#/components/schemas/protocol_response_item"
                type: array
              real_host:
                type: string
              service_publisher_assignments:
                items:
                  $ref: "#/components/schemas/service_publisher_assignment_item"
                type: array
              tags:
                items:
                  $ref: "#/components/schemas/tag_item"
                type: array
              trust_self_signed_certs:
                type: boolean
              use_publisher_dns:
                type: boolean
            type: object
          status:
            enum:
              - success
              - not found
            type: string
          total:
            format: int32
            type: integer
        type: object
      type: array
    private_apps_put_request:
      properties:
        allow_unauthenticated_cors:
          type: boolean
        allow_uri_bypass:
          type: boolean
        uribypass_header_value:
          type: string
        bypass_uris:
          items:
            type: string
          type: array
        app_name:
          type: string
        app_option:
          type: object
        clientless_access:
          type: boolean
        host:
          type: string
        id:
          format: int32
          type: integer
        is_user_portal_app:
          type: boolean
        protocols:
          items:
            $ref: "#/components/schemas/protocol_item"
          type: array
        publisher_tags:
          items:
            $ref: "#/components/schemas/tag_item_no_id"
          type: array
        publishers:
          items:
            $ref: "#/components/schemas/publisher_item"
          type: array
        real_host:
          type: string
        tags:
          items:
            $ref: "#/components/schemas/tag_item_no_id"
          type: array
        trust_self_signed_certs:
          type: boolean
        use_publisher_dns:
          type: boolean
      type: object
    private_apps_request:
      properties:
        allow_unauthenticated_cors:
          type: boolean
        allow_uri_bypass:
          type: boolean
        uribypass_header_value:
          type: string
        bypass_uris:
          items:
            type: string
          type: array
        app_name:
          type: string
        app_option:
          type: object
        clientless_access:
          type: boolean
        host:
          type: string
        is_user_portal_app:
          type: boolean
        protocols:
          items:
            $ref: "#/components/schemas/protocol_item"
          type: array
        publisher_tags:
          items:
            $ref: "#/components/schemas/tag_item_no_id"
          type: array
        publishers:
          items:
            $ref: "#/components/schemas/publisher_item"
          type: array
        real_host:
          type: string
        tags:
          items:
            $ref: "#/components/schemas/tag_item_no_id"
          type: array
        trust_self_signed_certs:
          type: boolean
        use_publisher_dns:
          type: boolean
      type: object
    private_apps_response:
      items:
        properties:
          data:
            properties:
              allow_unauthenticated_cors:
                type: boolean
              allow_uri_bypass:
                type: boolean
              uribypass_header_value:
                type: string
              bypass_uris:
                items:
                  type: string
                type: array
              app_option:
                type: object
              clientless_access:
                type: boolean
              host:
                type: string
              id:
                format: int32
                type: integer
              is_user_portal_app:
                type: boolean
              name:
                type: string
              protocols:
                items:
                  $ref: "#/components/schemas/protocol_response_item"
                type: array
              real_host:
                type: string
              service_publisher_assignments:
                items:
                  $ref: "#/components/schemas/service_publisher_assignment_item"
                type: array
              tags:
                items:
                  $ref: "#/components/schemas/tag_item"
                type: array
              trust_self_signed_certs:
                type: boolean
              use_publisher_dns:
                type: boolean
            type: object
          status:
            enum:
              - success
              - not found
            type: string
        type: object
      type: array
    private_apps_response_400:
      properties:
        result:
          type: string
        status:
          example: 400
          type: integer
      type: object
    protocol_item:
      properties:
        port:
          type: string
        type:
          type: string
      type: object
    protocol_response_item:
      properties:
        id:
          format: int32
          type: integer
        port:
          type: string
        service_id:
          format: int32
          type: integer
        transport:
          type: string
      type: object
    publisher_item:
      properties:
        publisher_id:
          type: string
        publisher_name:
          type: string
      type: object
    service_publisher_assignment_item:
      properties:
        primary:
          type: boolean
        publisher_id:
          format: int32
          type: integer
        reachability:
          properties:
            error_code:
              format: int32
              type: integer
            error_string:
              type: string
            reachable:
              type: boolean
          type: object
        service_id:
          format: int32
          type: integer
      type: object
    tag_item:
      properties:
        tag_id:
          format: int32
          type: integer
        tag_name:
          type: string
      type: object
    tag_item_no_id:
      properties:
        tag_name:
          type: string
      type: object
info:
  description: NPA private apps CRUD operations.
  title: npa_private_apps
  version: 1.0.0
openapi: 3.0.0
paths:
  /steering/apps/private:
    get:
      description: Get list of private applications
      parameters:
        - description: Return values only from specified fields
          in: query
          name: fields
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_get_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Get list of private applications
    post:
      description: Create a private application
      parameters:
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/private_apps_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Create a private application
    x-netskope-params:
      apiGroup: npa_apps_private
      customerFacing: true
      rateLimit:
        readRoutes:
          hour: 1000
          second: 30
        writeRoutes:
          hour: 1000
          second: 30
      serviceConfig: provisioner-pycore-ws
      version: 2
  /steering/apps/private/getpolicyinuse:
    post:
      description: Retrieve number of policy in use for specified private apps
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ids:
                  items:
                    type: string
                  type: array
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    data:
                      properties:
                        token:
                          type: string
                      type: object
                    status:
                      enum:
                        - success
                        - not found
                      type: string
                  type: object
                type: array
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Retrieve number of policy in use for specified private apps
    x-netskope-params:
      apiGroup: npa_apps_private
      customerFacing: true
      rateLimit:
        readRoutes:
          hour: 1000
          second: 30
        writeRoutes:
          hour: 1000
          second: 30
      serviceConfig: provisioner-pycore-ws
      version: 2
  /steering/apps/private/{private_app_id}:
    delete:
      description: Delete a private application based on private app id
      parameters:
        - description: private apps id
          in: path
          name: private_app_id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  status:
                    enum:
                      - success
                      - error
                    type: string
                type: object
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Delete a private application
    get:
      description: Get a private application based on private app id
      parameters:
        - description: private apps id
          in: path
          name: private_app_id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Get a private application
    patch:
      description: Patch a private application based on private app id
      parameters:
        - description: private apps id
          in: path
          name: private_app_id
          required: true
          schema:
            format: int32
            type: integer
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/private_apps_put_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Patch a private application
    put:
      description: Update a private application based on private app id
      parameters:
        - description: private apps id
          in: path
          name: private_app_id
          required: true
          schema:
            format: int32
            type: integer
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/private_apps_put_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/private_apps_response_400"
          description: Invalid request
      summary: Update a private application
    x-netskope-params:
      apiGroup: npa_apps_private
      customerFacing: true
      rateLimit:
        readRoutes:
          hour: 1000
          second: 30
        writeRoutes:
          hour: 1000
          second: 30
      serviceConfig: provisioner-pycore-ws
      version: 2
