components:
  schemas:
    tag_item:
      properties:
        tag_id:
          format: int32
          type: integer
        tag_name:
          type: string
      type: object
    tag_request:
      properties:
        id:
          type: string
        ids:
          items:
            type: string
          type: array
        publisher_tags:
          items:
            $ref: "#/components/schemas/tag_item"
          type: array
        tags:
          items:
            $ref: "#/components/schemas/tag_item"
          type: array
      type: object
    tag_response:
      items:
        properties:
          data:
            properties:
              tag_id:
                format: int32
                type: integer
              tag_name:
                type: string
            type: object
          status:
            enum:
              - success
              - not found
            type: string
        type: object
      type: array
    tag_response_400:
      properties:
        result:
          type: string
        status:
          example: 400
          type: integer
      type: object
info:
  description: NPA Private app tag operations.
  title: npa_private_app_tags
  version: 1.0.0
openapi: 3.0.0
paths:
  /steering/apps/private/tags:
    delete:
      description: Bulk delete tags for specified private apps
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tag_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: bulk delete tags for specified private apps
    get:
      description: Get list of private app tags
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: "Get list of private app tags "
    patch:
      description: Bulk update tags to associate with specified private apps
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tag_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: bulk update tags to associate with specified private apps
    post:
      description: Create tags for private apps
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tag_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: create tags for private apps
    x-netskope-params:
      apiGroup: npa_private_tag
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
  /steering/apps/private/tags/getpolicyinuse:
    post:
      description: Retrieve number of policy in use for specified tags
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ids:
                  items:
                    type: string
                  type: array
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    data:
                      properties:
                        token:
                          type: string
                      type: object
                    status:
                      enum:
                        - success
                        - not found
                      type: string
                  type: object
                type: array
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: Retrieve number of policy in use for specified tags
    x-netskope-params:
      apiGroup: npa_private_tag
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
  /steering/apps/private/tags/{tag_id}:
    delete:
      description: Delete a private app tag based on tag id
      parameters:
        - description: tag id
          in: path
          name: tag_id
          required: true
          schema:
            format: int32
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tag_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  status:
                    enum:
                      - success
                      - error
                    type: string
                type: object
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: Delete a private app tag based on tag id
    get:
      description: Get a private app tag based on tag id
      parameters:
        - description: tag id
          in: path
          name: tag_id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: Get a private app tag based on tag id
    put:
      description: Update a private app tag based on tag id
      parameters:
        - description: tag id
          in: path
          name: tag_id
          required: true
          schema:
            format: int32
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tag_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tag_response_400"
          description: Invalid request
      summary: Update a private app tag based on tag id
    x-netskope-params:
      apiGroup: npa_private_tag
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
