components:
  schemas:
    SampleErrorResponse:
      properties:
        error_message:
          type: string
        status:
          type: string
      type: object
    TssScanAPIRequest:
      properties:
        file:
          format: binary
          type: string
      type: object
    TssScanAPIResponse:
      properties:
        jobid:
          description: jobid to be used to get analysis report for scan
          type: string
        md5:
          type: string
        requests_served:
          description: Requests served since mid night GMT
          format: int32
          type: integer
        sha256:
          type: string
        status:
          type: string
      type: object
    TssScanReportResponse:
      properties:
        av_detection:
          description: AV detection
          type: object
        dropped:
          description: Information on files dropped by the malware and dumped by sandbox
          items: {}
          type: array
        jobid:
          type: string
        md5:
          type: string
        network:
          description:
            Network information, such as DNS traffic, domains, IPs, HTTP
            requests and SMTP traffic
          type: object
        observed_behavior:
          description: Behavioral summary
          type: object
        process_tree:
          description: Process tree
          items: {}
          type: array
        requests_served:
          description: Requests served since mid night GMT
          format: int32
          type: integer
        sha256:
          type: string
        status:
          type: string
        verdict:
          type: string
      required:
        - status
        - jobid
        - md5
        - sha256
        - requests_served
        - verdict
      type: object
info:
  description:
    " Advanced Threat Protection is Netskope application to host various\
    \ services related to scanning a file and generate corresponding scan reports\
    \ \n ### Feature description: \n Provides a mechanism to retrieve sandbox observed\
    \ behaviors and forensics analysis (e.g. MITRE TTPs)  for SOC analysts \n ###\
    \ Required License: \n Advanced Threat protection \n"
  title: Advanced Threat Protection
  version: 1.0.0
openapi: 3.0.0
paths:
  /atp/scans/filescan:
    post:
      description:
        "API to submit a password protected .zip file with password infected
        for scan by Netskope sandbox(Supported member file types in the zip: .exe,
        .pdf, .doc, .xls, .ppt and .rtf. Total files in the zip : 1. File size: up
        to 16MB, up to 1000 files per day)"
      parameters:
        - description: scantype eg sandbox, at-present only supported value is sandbox
          in: query
          name: scantype
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/TssScanAPIRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                jobid: 8ffdffbdbe1efccb32edfaca
                md5: b6cf006580b0043fcaa12d4c6b21525f
                requests_served: 1
                sha256: 50a67efa667ddc713f6c3ec9ac16d6e14baa1c9c0b952968e5f8ac3ea827bde5
                status: Ok
              schema:
                $ref: "#/components/schemas/TssScanAPIResponse"
          description: Successful operation
        "400":
          content:
            application/json:
              example:
                error_message: Please use right request to query
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Invalid request
        "401":
          content:
            application/json:
              example:
                error_message: Please make sure you are authorized for this service
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Unauthorized request
        "429":
          content:
            application/json:
              example:
                error_message: Rate limit exceeded, please try later
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Rate limit exceeded
        "500":
          content:
            application/json:
              example:
                error_message: Please report this error to Netskope or query again
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Internal error
      summary: Send file scan request to sandbox
      x-codegen-request-body-name: body
    x-netskope-params:
      apiGroup: atpsvc
      customerFacing: true
      serviceConfig: atp
      version: 2
  /atp/scans/reports/{jobid}:
    get:
      description:
        "Get analysis report of a file submitted for scan by sandbox, Using\
        \ jobid returned in filescan request \n (Up to 10,000 requests per day)"
      parameters:
        - description: jobid returned in 'scans/filescan' api request
          in: path
          name: jobid
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              example:
                av_detection:
                  malware_name: Trojan.GenericKD.45988023
                dropped:
                  - crc32: B2F917CB
                    filepath: C:\Windows\system\WYutAwK.exe
                    name: 8d5fcb055894b517_wyutawk.exe
                    sha1: 1761ab726d1c185a1764092a81a4ce9b9b530478
                    sha256: 8d5fcb055894b51728df60b7d42dc76566ae47f63d6e071df9676a98a848bd17
                    sha512: 19b57cf3a0ee88d8e78ae5319211cb5e1e5d87ab8e178314a8a991f03080093f3c362a565fe4933ad97025e3fa8d01e250de4d114fffb8c8d8e4737528c674ec
                    size: 1997159
                    ssdeep: 49152:dezaTF8FcNkNdfE0pZ9oztQwI35aIwC+A8Jh1Aa98L0:demTLkNdfE0pZ34
                    type:
                      PE32+ executable (console) x86-64 (stripped to external PDB),
                      for MS Windows
                    urls: []
                    yara: []
                  - crc32: A87A41D6
                    filepath: C:\Windows\system\xFOjbUK.exe
                    name: d9bcb6b68cb6e457_xfojbuk.exe
                    sha1: 9198f83cf2b814faa270bc8163c7962f8075e529
                    sha256: d9bcb6b68cb6e45733f17b8456551ae6cfcd03ce1caf6a30e3f646d17466ba29
                    sha512: 4c1317006da199a5f1c0092e5c82010ee35538e1d5faa59204711cf849131b2544d463d3b145cf81183d5a9d56aabd4083ccf3d37fc89aeaec6290c1dfc139ee
                    size: 2068758
                    ssdeep: 49152:dezaTF8FcNkNdfE0pZ9oztQwI35aIwC+A8Jh1Aa98Ll:demTLkNdfE0pZ3R
                    type:
                      PE32+ executable (console) x86-64 (stripped to external PDB),
                      for MS Windows
                    urls: []
                    yara: []
                  - crc32: CF867A9E
                    filepath: C:\Windows\system\GZvLXUR.exe
                    name: c8bd0ac8d6c2299a_gzvlxur.exe
                    sha1: 7c05654ba0af9aafc02d9297e49906f247854801
                    sha256: c8bd0ac8d6c2299a495b50854832d683646a103d90096839131f2fdaf21945aa
                    sha512: 7191d2f4cb813c6eb612d4c33ed94ca28f0ab91edf3d43def17da1b3033a3fec7ca608b6637dee5eec90b60f092d7ad772639f51d82278797fd08707d7284d7c
                    size: 2055602
                    ssdeep: 49152:dezaTF8FcNkNdfE0pZ9oztQwI35aIwC+A8Jh1Aa98LmE:demTLkNdfE0pZ3b
                    type:
                      PE32+ executable (console) x86-64 (stripped to external PDB),
                      for MS Windows
                    urls: []
                    yara: []
                jobid: b56dd8b646f7d99acb78b723
                md5: 52de0df53e1d56e3bff153bcfd8d1938
                network:
                  dns: []
                  dns_servers: []
                  hosts: []
                  http: []
                  icmp: []
                  mitm: []
                  pcap_sha256: 2e95374097894902d81f40511e84a2f1a00e439d42ac42722c1255a0956b24d8
                  smtp: []
                  smtp_ex: []
                  tcp: []
                  tls: []
                  udp:
                    - dport: 138
                      dst: 192.168.101.255
                      offset: 292
                      sport: 138
                      src: 192.168.101.2
                      time: 47.72846508026123
                observed_behavior:
                  Defense Evasion:
                    Attempts to remove evidence of file being downloaded from the Internet:
                      details: []
                      references: []
                      score: 3
                      severity: high
                      ttp: {}
                    Checks if process is being debugged by a debugger:
                      details: []
                      references: []
                      score: 1
                      severity: low
                      ttp: {}
                    Executed a process and injected code into it probably while unpacking:
                      details: []
                      references: []
                      score: 5
                      severity: high
                      ttp: {}
                    score: 5
                    severity: high
                  Discovery:
                    Checks amount of memory in system this can be used to detect virtual machines that have a low amount of memory available:
                      details: []
                      references: []
                      score: 1
                      severity: low
                      ttp: {}
                    Detects Avast Antivirus through the presence of a library:
                      details: []
                      references: []
                      score: 3
                      severity: high
                      ttp: {}
                    score: 3
                    severity: high
                  Execution:
                    Command line console output was observed:
                      details: []
                      references: []
                      score: 1
                      severity: low
                      ttp: {}
                    Creates executable files on the filesystem:
                      details: []
                      references: []
                      score: 2
                      severity: medium
                      ttp:
                        T1129:
                          long:
                            The Windows module loader can be instructed to load
                            DLLs from arbitrary local paths and arbitrary Universal
                            Naming Convention (UNC) network paths. This functionality
                            resides in NTDLL.dll and is part of the Windows Native
                            API which is called from functions like CreateProcess(),
                            LoadLibrary(), etc. of the Win32 API.
                          short: Execution through Module Load
                    Drops an executable to the user AppData folder:
                      details: []
                      references: []
                      score: 2
                      severity: medium
                      ttp: {}
                    score: 2
                    severity: medium
                  Persistence:
                    Installs itself for autorun at Windows startup:
                      details: []
                      references: []
                      score: 3
                      severity: high
                      ttp: {}
                    score: 3
                    severity: high
                  Privilege Escalation:
                    Uses Windows utilities for basic Windows functionality:
                      details: []
                      references:
                        - http://blog.jpcert.or.jp/2016/01/windows-commands-abused-by-attackers.html
                      score: 2
                      severity: medium
                      ttp:
                        T1053:
                          long:
                            Utilities such as at and schtasks, along with the
                            Windows Task Scheduler, can be used to schedule programs
                            or scripts to be executed at a date and time. A task can
                            also be scheduled on a remote system, provided the proper
                            authentication is met to use RPC and file and printer
                            sharing is turned on. Scheduling a task on a remote system
                            typically required being a member of the Administrators
                            group on the the remote system.
                          short: Scheduled Task
                    score: 2
                    severity: medium
                  score: 5
                  severity: high
                process_tree:
                  - children:
                      - children:
                          - children:
                              - children: []
                                command_line:
                                  reg  add "HKEY_CURRENT_USER\Software\Microsoft\Windows
                                  NT\CurrentVersion\Windows" /v "Load" /d "C:\Users\jonney\AppData\Roaming\Microsoft\Windows\ScreenToGif\netprotocol.exe"
                                  /f
                                first_seen: 1642096011.78125
                                pid: 944
                                ppid: 1000
                                process_name: reg.exe
                                track: true
                            command_line:
                              '"C:\Windows\System32\cmd.exe" /c reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows
                              NT\CurrentVersion\Windows" /v "Load" /d "C:\Users\jonney\AppData\Roaming\Microsoft\Windows\ScreenToGif\netprotocol.exe"
                              /f'
                            first_seen: 1642096011.53125
                            pid: 1000
                            ppid: 1716
                            process_name: cmd.exe
                            track: true
                          - children:
                              - children: []
                                command_line:
                                  C:\Windows\Microsoft.NET\Framework\v2.0.50727\cvtres.exe
                                  /NOLOGO /READONLY /MACHINE:IX86 "/OUT:C:\Users\jonney\AppData\Local\Temp\RES5EDF.tmp"
                                  "C:\Users\jonney\AppData\Local\Temp\vbc3CF42EB061D045B1AD5258EEF0E413F.TMP"
                                first_seen: 1642096012.84375
                                pid: 812
                                ppid: 1468
                                process_name: cvtres.exe
                                track: true
                            command_line:
                              '"C:\Windows\Microsoft.NET\Framework\v2.0.50727\vbc.exe"
                              /noconfig @"C:\Users\jonney\AppData\Local\Temp\kv3iebxi.cmdline"'
                            first_seen: 1642096012.125
                            pid: 1468
                            ppid: 1716
                            process_name: vbc.exe
                            track: true
                        command_line:
                          '"C:\Users\jonney\AppData\Roaming\Microsoft\Windows\ScreenToGif\netprotocol.exe"
                          -n'
                        first_seen: 1642096009.875
                        pid: 1716
                        ppid: 548
                        process_name: netprotocol.exe
                        track: true
                    command_line: '"C:\Users\jonney\AppData\Local\Temp\file.exe" '
                    first_seen: 1642096007.90625
                    pid: 548
                    ppid: 292
                    process_name: file.exe
                    track: true
                requests_served: 1
                sha256: 57f5557ef6d17ae6495db0472df0ffb4cb041fe4b87c458a190294151076803b
                status: Ok
                verdict: malicious
              schema:
                $ref: "#/components/schemas/TssScanReportResponse"
          description: Succesfully received scan analysis report
        "202":
          content:
            application/json:
              example:
                jobid: 8ffdffbdbe1efccb32edfaca
                md5: b6cf006580b0043fcaa12d4c6b21525f
                requests_served: 1
                sha256: 50a67efa667ddc713f6c3ec9ac16d6e14baa1c9c0b952968e5f8ac3ea827bde5
                status: InProgress
              schema:
                $ref: "#/components/schemas/TssScanReportResponse"
          description: Scan in progress
        "400":
          content:
            application/json:
              example:
                error_message: Please use right request to query
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Invalid request
        "401":
          content:
            application/json:
              example:
                error_message: Please make sure you are authorized for this service
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Unauthorized request
        "403":
          content:
            application/json:
              example:
                error_message: Not authorized to check this sample report
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Not authorized to check this sample report
        "429":
          content:
            application/json:
              example:
                error_message: Rate limit exceeded, please try later
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Rate limit exceeded
        "500":
          content:
            application/json:
              example:
                error_message: Please report this error to Netskope
                status: Error
              schema:
                $ref: "#/components/schemas/SampleErrorResponse"
          description: Please report this error to Netskope
      summary: Get scan analysis report
    x-netskope-params:
      apiGroup: atpsvc
      customerFacing: true
      serviceConfig: atp
      version: 2
