openapi: 3.0.0
info:
  title: npa_policy
  description: NPA policy CRUD operations.
  version: 1.0.0
components:
  schemas:
    npa_policygroup_request:
      type: object
      x-speakeasy-entity: NPAPolicyGroup
      required: # Ideally required params should be specified
        - group_name
        - group_order
       
      properties:
        group_name:
          type: string
        #### This causes group order to be nested in group order which is not correct
        #group_order:
        #  type: object
        #  properties:
        #    group_order:
        #      type: object
        #      properties:
        #        order:
        #          type: string
        #          enum:
        #            - before
        #            - after
        #        group_id:
        #          type: string
        #          example: '1'
        # Should Be this...
        group_order:
          type: object
          required:
            - order
            - group_id
          properties:
            order:
              type: string
              enum:
                - before
                - after
            group_id:
              type: string
              example: '1'

        ### This should be in the response        
        # modify_type:
        #  type: string
        # modify_by:
        #  type: string
    npa_policygroup_patch_request:
      type: object
      x-speakeasy-entity: NPAPolicyGroup   
      properties:
        group_name:
          type: string
        group_order:
          type: object
          properties:
            order:
              type: string
              enum:
                - before
                - after
            group_id:
              type: string
              example: '1'
              
    npa_policygroup_response_item:
      type: object
      x-speakeasy-entity: NPAPolicyGroup
      properties:
        group_id:
          x-speakeasy-name-override: id
          # This is a string
          #type: integer
          type: string
        group_name:
          type: string
        modify_type:
          x-speakeasy-ignore: true 
          type: string
        modify_time:
          x-speakeasy-ignore: true
          type: string
        can_be_edited_deleted:
          x-speaskeasy-ignore: true
          # This is a string
          #type: integer
          type: string
        group_type:
          x-speakeasy-ignore: true
          #This is a string
          #type: integer
          type: string
#### group_prod_id does not exist in the output of a post
#       group_prod_id: # This doesn't appear to be returned but I bet it is a string
#         x-speakeasy-ignore: true 
#         type: integer
### group_pinned_id does not exist in the output of a post
#        group_pinned_id: # This doesn't appear to be returned but I bet it is a string
#          x-speakeasy-ignore: true
#          type: integer

    npa_policygroup_response:
      type: object
      x-speakeasy-entity: PolicyGroupList
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/npa_policygroup_response_item"
    npa_policygroup_response_400:
      type: object
      properties:
        status:
          type: integer
          example: 400
        result:
          type: string
paths:
  "/policy/npa/policygroups":
    x-netskope-params:
      serviceConfig: provisioner-pycore-ws
      version: 2
      customerFacing: true
      apiGroup: npa_policygroup
    get:
      summary: Get list of npa policy groups
      description: Get list of npa policy groups
      x-speakeasy-entity-operation: PolicyGroupList#read
      operationId: getNPAPolicyGroups
      parameters:
        - name: fields
          in: query
          required: false
          x-speakeasy-terraform-ignore: true
          description: Return values only from specified fields
          schema:
            type: string
        - name: filter
          in: query
          required: false
          description: Query string based on query operaters
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Max number of policy groups to retrieve. Default will be all
            policy groups.
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          description: The offset of the first policy group in the list to retrieve.
          schema:
            type: integer
        - name: sortby
          in: query
          required: false
          description: Sort retrieved policy group by specified field. Default is policy
            group id
          schema:
            type: string
        - name: sortorder
          in: query
          required: false
          description: Sort in either asc or desc order. The default is asc order
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response_400"
    post:
      summary: Create a npa policy group
      description: Create a npa policy group
      x-speakeasy-entity-operation: NPAPolicyGroup#create
      operationId: createNPAPolicyGroups
      parameters:
        - name: silent
          in: query
          x-speakeasy-terraform-ignore: true
          required: false
          description: flag to skip output except status code
          schema:
            type: string
            enum:
              - '1'
              - '0'
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/npa_policygroup_request"
        required: true
      responses:
        '200':
          description: successful operation
          #### This should look like.....
          # content:
          #  application/json:
          #    schema:
          #      "$ref": "#/components/schemas/npa_policygroup_response_item"
          #
          # This...
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    x-speakeasy-ignore: true
                    type: string
                    enum:
                      - success
                      - error
                  data:
                    type: array
                    "$ref": "#/components/schemas/npa_policygroup_response_item"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response_400"
  "/policy/npa/policygroups/{id}":
    x-netskope-params:
      serviceConfig: provisioner-pycore-ws
      version: 2
      customerFacing: true
      apiGroup: npa_policygroup
    delete:
      summary: Delete a npa policy group
      description: Delete a npa policy group with group id
      x-speakeasy-entity-operation: NPAPolicyGroup#delete
      operationId: deleteNPAPolicyGroups
      parameters:
        - name: id
          in: path
          required: true
          description: npa policy group id
          schema:
            # This is actually a string
            #type: integer
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - success
                      - error
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response_400"
    patch:
      summary: Patch a npa policy group
      description: Patch a npa policy group based on group id
      operationId: patchNPAPolicyGroupsById
      x-speakeasy-entity-operation: NPAPolicyGroup#update
      parameters:
        - name: id
          in: path
          required: true
          description: policy group rule id
          schema:
            #type: integer #Actually a string
            type: string
        - name: silent
          in: query
          required: false
          x-speakeasy-terraform-ignore: true
          description: flag to skip output except status code
          schema:
            type: string
            enum:
              - '1'
              - '0'
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/npa_policygroup_patch_request"
        required: true
      responses:
        '200':
          description: successful operation
          #### This should look like.....
          # content:
          #  application/json:
          #    schema:
          #      "$ref": "#/components/schemas/npa_policygroup_response_item"
          #
          # This...
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    x-speakeasy-ignore: true
                    type: string
                    enum:
                      - success
                      - error
                  data:
                    type: array
                    "$ref": "#/components/schemas/npa_policygroup_response_item"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response_400"
    get:
      summary: Get a npa policy group
      description: Get a npa policy group based on group id
      x-speakeasy-entity-operation: NPAPolicyGroup#read
      operationId: getNPAPolicyGroupsById
      parameters:
        - name: id
          in: path
          required: true
          description: npa policy group id
          schema:
            #type: integer #Actually a string
            type: string
      responses:
        '200':
          description: successful operation
          #### This should look like.....
          # content:
          #  application/json:
          #    schema:
          #      "$ref": "#/components/schemas/npa_policygroup_response_item"
          #
          # This...
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    x-speakeasy-ignore: true
                    type: string
                    enum:
                      - success
                      - error
                  data:
                    type: array
                    "$ref": "#/components/schemas/npa_policygroup_response_item"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/npa_policygroup_response_400"
