components:
  schemas:
    npa_policygroup_request:
      properties:
        group_name:
          type: string
        group_order:
          properties:
            group_order:
              properties:
                group_id:
                  example: "1"
                  type: string
                order:
                  enum:
                    - before
                    - after
                  type: string
              type: object
          type: object
        modify_by:
          type: string
        modify_type:
          type: string
      type: object
    npa_policygroup_response:
      items:
        $ref: "#/components/schemas/npa_policygroup_response_item"
      type: array
    npa_policygroup_response_400:
      properties:
        result:
          type: string
        status:
          example: 400
          type: integer
      type: object
    npa_policygroup_response_item:
      properties:
        can_be_edited_deleted:
          type: integer
        group_id:
          type: integer
        group_name:
          type: string
        group_pinned_id:
          type: integer
        group_prod_id:
          type: integer
        group_type:
          type: integer
        modify_time:
          type: string
        modify_type:
          type: string
      type: object
info:
  description: NPA policy CRUD operations.
  title: npa_policy
  version: 1.0.0
openapi: 3.0.0
paths:
  /policy/npa/policygroups:
    get:
      description: Get list of npa policy groups
      parameters:
        - description: Return values only from specified fields
          in: query
          name: fields
          required: false
          schema:
            type: string
        - description: Query string based on query operaters
          in: query
          name: filter
          required: false
          schema:
            type: string
        - description:
            Max number of policy groups to retrieve. Default will be all
            policy groups.
          in: query
          name: limit
          required: false
          schema:
            type: integer
        - description: The offset of the first policy group in the list to retrieve.
          in: query
          name: offset
          required: false
          schema:
            type: integer
        - description:
            Sort retrieved policy group by specified field. Default is policy
            group id
          in: query
          name: sortby
          required: false
          schema:
            type: string
        - description: Sort in either asc or desc order. The default is asc order
          in: query
          name: sortorder
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_400"
          description: Invalid request
      summary: Get list of npa policy groups
    post:
      description: Create a npa policy group
      parameters:
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/npa_policygroup_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_item"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_400"
          description: Invalid request
      summary: Create a npa policy group
    x-netskope-params:
      apiGroup: npa_policygroup
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
  /policy/npa/policygroups/{id}:
    delete:
      description: Delete a npa policy group with group id
      parameters:
        - description: npa policy group id
          in: path
          name: id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  status:
                    enum:
                      - success
                      - error
                    type: string
                type: object
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_400"
          description: Invalid request
      summary: Delete a npa policy group
    get:
      description: Get a npa policy group based on group id
      parameters:
        - description: npa policy group id
          in: path
          name: id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_item"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_400"
          description: Invalid request
      summary: Get a npa policy group
    patch:
      description: Patch a npa policy group based on group id
      parameters:
        - description: policy group rule id
          in: path
          name: id
          required: true
          schema:
            format: int32
            type: integer
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/npa_policygroup_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_item"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/npa_policygroup_response_400"
          description: Invalid request
      summary: Patch a npa policy group
    x-netskope-params:
      apiGroup: npa_policygroup
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
