components:
  schemas:
    DeletedUrllist:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          example: Deleted
          type: string
        name:
          type: string
        pending:
          example: 1
          type: integer
      type: object
    RequestSchema:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        name:
          type: string
      type: object
    UpdatedUrllist:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          example: Edited
          type: string
        name:
          type: string
        pending:
          example: 1
          type: integer
      type: object
    Urllist:
      properties:
        data:
          properties:
            type:
              enum:
                - exact
                - regex
              type: string
            urls:
              items:
                example: www.test.com
                type: string
              type: array
          type: object
        id:
          format: int64
          type: integer
        modify_by:
          example: Netskope API
          type: string
        modify_time:
          example: "1997-01-01 00:00:00"
          type: string
        modify_type:
          enum:
            - Created
            - Edited
            - Deleted
          type: string
        name:
          type: string
        pending:
          type: integer
      type: object
info:
  description: ""
  title: ""
  version: ""
openapi: 3.0.0
paths:
  /policy/urllist:
    get:
      description:
        Returns an array of URL list objects containing ID, name, URLs,
        type, modify type, modify by, modify time, and pending information.
      parameters:
        - description: Get a list of only applied (0) or pending (1) URL lists
          in: query
          name: pending
          required: false
          schema:
            enum:
              - 0
              - 1
            type: number
        - description: Data values to return in response call. Defaults to all values
          in: query
          name: field
          required: false
          schema:
            enum:
              - id
              - name
              - data
              - modify_type
              - modify_time
              - modify_by
              - pending
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Urllist"
                type: array
          description: Succesfully got URL lists
      summary: Get all applied and pending URL lists
    post:
      description: Create a new URL list configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Urllist"
                type: array
          description: successful operation
      summary: Create a new URL list.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/deploy:
    post:
      description: Applies currently pending changes for URL lists. To ensure efficiency, avoid unncessary network overhead and reliable deployments, we recommend batching all desired changes and applying them in a single deploy call rather than making single changes and initiating multiple deploy calls.
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Urllist"
                type: array
          description: Succesfully deployed URL lists
      summary: Apply pending URL list changes.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/file:
    post:
      description:
        "Upload multiple URL list configurations via a JSON file. \n\n\
        \ URL lists NOT containing an ID will create new URL lists. \n\n URL lists\
        \ containing an ID will replace an existing URL list with the same ID."
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                urllist:
                  format: binary
                  type: string
              type: object
        description:
          '``` { "items": [ { "name": "string", "data": { "urls": ["www.example.com"],
          "type": "exact" } } ] } ```'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Urllist"
          description: successful operation
      summary: Upload multiple configurations via a JSON file
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/{id}:
    delete:
      description: Mark a URL list as pending deletion.
      parameters:
        - content:
            text/plain:
              schema:
                type: number
          description: ID of the URL list
          in: path
          name: id
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeletedUrllist"
          description: successful operation
      summary: Delete a URL list.
    get:
      description: Get the configuration of the given URL list ID.
      parameters:
        - content:
            text/plain:
              schema:
                type: number
          description: ID of the URL list
          in: path
          name: id
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Urllist"
          description: successful operation
      summary: Get URL list by ID.
    put:
      description: Completely replace the configuration of the given URL list ID.
      operationId: updateUser
      parameters:
        - content:
            text/plain:
              schema:
                type: number
          description: ID of the URL list
          in: path
          name: id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedUrllist"
          description: successful operation
      summary: Replace a URL list configuration.
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
  /policy/urllist/{id}/{action}:
    patch:
      description: Update name, URLs, and/or type of URL list object
      parameters:
        - content:
            text/plain:
              schema:
                type: number
          description: ID of the URL list
          in: path
          name: id
          required: true
        - content:
            text/plain:
              schema:
                type: string
          description: Replace or append to current URLs
          in: path
          name: action
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        description: New URL list object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedUrllist"
          description: successful operation
      summary: Patch URL list
    x-netskope-params:
      apiGroup: urllist
      customerFacing: true
      serviceConfig: webui-api
      version: 2
