components:
  schemas:
    trafficclasses_delete_request_items:
      items:
        example: 1
        type: integer
      type: array
    trafficclasses_get_response_200_item:
      properties:
        description:
          example: description
          type: string
        id:
          example: 1
          type: integer
        modified_type:
          example: created
          type: string
        name:
          example: traffic_class1
          type: string
      type: object
    trafficclasses_get_response_200_items:
      properties:
        count:
          example: 1
          type: integer
        data:
          items:
            $ref: "#/components/schemas/trafficclasses_get_response_200_item"
          type: array
        status:
          example: 200
          type: integer
      type: object
    trafficclasses_patch_request_item:
      properties:
        description:
          example: description
          type: string
        id:
          example: 1
          type: integer
        name:
          example: traffic_class1
          type: string
      type: object
    trafficclasses_patch_request_items:
      items:
        $ref: "#/components/schemas/trafficclasses_patch_request_item"
      type: array
    trafficclasses_patch_response_200:
      properties:
        data:
          items:
            $ref: "#/components/schemas/trafficclasses_get_response_200_item"
          type: array
        status:
          example: 200
          type: integer
      type: object
    trafficclasses_post_request_item:
      properties:
        description:
          example: description
          type: string
        name:
          example: traffic_class1
          type: string
      type: object
    trafficclasses_post_request_items:
      items:
        $ref: "#/components/schemas/trafficclasses_post_request_item"
      type: array
    trafficclasses_post_response_200:
      properties:
        data:
          items:
            $ref: "#/components/schemas/trafficclasses_get_response_200_item"
          type: array
        status:
          example: 200
          type: integer
      type: object
    trafficclasses_response_200:
      properties:
        data:
          example: success_200
          type: string
        status:
          example: 200
          type: integer
      type: object
    trafficclasses_response_400:
      properties:
        data:
          example: error_400
          type: string
        status:
          example: 400
          type: integer
      type: object
    trafficclasses_response_403:
      properties:
        data:
          example: error_403
          type: string
        status:
          example: 403
          type: integer
      type: object
    trafficclasses_response_404:
      properties:
        data:
          example: error_404
          type: string
        status:
          example: 404
          type: integer
      type: object
    trafficclasses_response_405:
      properties:
        data:
          example: error_405
          type: string
        status:
          example: 405
          type: integer
      type: object
    trafficclasses_response_409:
      properties:
        data:
          example: error_409
          type: string
        status:
          example: 409
          type: integer
      type: object
    trafficclasses_response_429:
      properties:
        data:
          example: error_429
          type: string
        status:
          example: 429
          type: integer
      type: object
    trafficclasses_response_500:
      properties:
        data:
          example: error_500
          type: string
        status:
          example: 500
          type: integer
      type: object
info:
  description: bandwidth control service trafficclasses related CRUD operations.
  title: bandwidthcontrol-service
  version: 1.0.0
openapi: 3.0.0
paths:
  /services/bandwidthcontrol/trafficclasses:
    get:
      description: API to get list of bandwidth control trafficclasses.
      parameters:
        - description: Offset to read from
          in: query
          name: offset
          required: false
          schema:
            default: 0
            type: integer
        - description: Limit on the result
          in: query
          name: limit
          required: false
          schema:
            default: 100
            maximum: 100
            minimum: 0
            type: integer
        - description: Sort column
          in: query
          name: sortby
          required: false
          schema:
            type: string
        - description: sort order - asc or desc. Default is asc
          in: query
          name: sortorder
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_get_response_200_items"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Get bandwidth control trafficclasses list
    patch:
      description:
        API to update bandwidth control trafficclasses using id. You can
        pass json body with fields that needs to be updated.
      parameters:
        - description: Value must be true or false. Defaults to false.
          in: query
          name: interactive
          required: false
          schema:
            example: false
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trafficclasses_patch_request_items"
        description: bandwidth control traffic class objects
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_patch_response_200"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_404"
          description: Not found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Update bandwidth control trafficclasses
    post:
      description:
        API to create new bandwidth control trafficclasses. You can pass
        json body with details.
      parameters:
        - description: Value must be true or false. Defaults to false.
          in: query
          name: interactive
          required: false
          schema:
            example: false
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trafficclasses_post_request_items"
        description: bandwidth control traffic class object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_post_response_200"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_409"
          description: Already exists
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Create bandwidth control trafficclasses
    x-netskope-params:
      apiGroup: trafficclasses
      customerFacing: true
      serviceConfig: qos
      version: 2
  /services/bandwidthcontrol/trafficclasses/deleteclasses:
    post:
      description: API to delete bandwidth control trafficclasses
      parameters:
        - description: Value must be true or false. Defaults to false.
          in: query
          name: interactive
          required: false
          schema:
            example: false
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trafficclasses_delete_request_items"
        description: bandwidth control traffic class id list
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_200"
          description: Successful operation
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_404"
          description: Not found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Delete bandwidth control trafficclasses
    x-netskope-params:
      apiGroup: trafficclasses
      customerFacing: true
      serviceConfig: qos
      version: 2
  /services/bandwidthcontrol/trafficclasses/{id}:
    delete:
      description: API to delete bandwidth control traffic class using id.
      parameters:
        - description: traffic class id
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: Value must be either true or false. Defaults to false.
          in: query
          name: interactive
          required: false
          schema:
            default: false
            type: boolean
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_200"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_404"
          description: Not found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Delete bandwidth control traffic class
    get:
      description: API to get bandwidth control traffic class using id.
      parameters:
        - description: traffic class id
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: Provide comma separated list of fields to be displayed
          in: query
          name: fields
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_get_response_200_items"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_404"
          description: Not found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Get bandwidth control traffic class
    patch:
      description:
        API to update bandwidth control trafficclass using id. You can
        pass json body with fields that needs to be updated.
      parameters:
        - description: traffic class id to be updated
          in: path
          name: id
          required: true
          schema:
            type: integer
        - description: Value must be true or false. Defaults to false.
          in: query
          name: interactive
          required: false
          schema:
            example: false
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/trafficclasses_post_request_item"
        description: Bandwidth control traffic class object.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_patch_response_200"
          description: Successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_400"
          description: Invalid request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_403"
          description: Access forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_404"
          description: Not found
        "405":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_405"
          description: Method not allowed
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_429"
          description: Too many requests
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trafficclasses_response_500"
          description: Internal server error
      summary: Update bandwidth control trafficclass
    x-netskope-params:
      apiGroup: trafficclasses
      customerFacing: true
      serviceConfig: qos
      version: 2
