components:
  schemas:
    "200":
      properties:
        result:
          items:
            type: object
          type: array
        status:
          example: 200
          type: integer
      type: object
    "400":
      properties:
        message:
          type: string
        status:
          example: 400
          type: integer
      type: object
    publisher_response:
      properties:
        assessment:
          type: object
        common_name:
          type: string
        lbrokerconnect:
          type: boolean
        publisher_id:
          format: int32
          type: integer
        publisher_name:
          type: string
        publisher_upgrade_profile_id:
          format: int32
          type: integer
        registered:
          type: boolean
        status:
          enum:
            - connected
            - not registered
          type: string
        stitcher_id:
          format: int32
          type: integer
        tags:
          items:
            $ref: "#/components/schemas/tag_item"
          type: array
      type: object
    publisher_upgrade_profile_bulk_request:
      properties:
        publishers:
          properties:
            apply:
              properties:
                publisher_upgrade_profiles_id:
                  type: string
              type: object
            id:
              items:
                type: string
              type: array
          type: object
      type: object
    publisher_upgrade_profile_bulk_response:
      properties:
        data:
          items:
            $ref: "#/components/schemas/publisher_response"
          type: array
        status:
          enum:
            - success
            - not found
          type: string
        total:
          format: int32
          type: integer
      type: object
    publisher_upgrade_profile_get_response:
      properties:
        data:
          properties:
            docker_tag:
              type: string
            enabled:
              format: int32
              type: integer
            frequency:
              type: string
            id:
              format: int32
              type: integer
            name:
              type: string
            release_type:
              type: string
            timezone:
              type: string
          type: object
        status:
          enum:
            - success
            - not found
          type: string
        total:
          format: int32
          type: integer
      type: object
    publisher_upgrade_profile_post_request:
      properties:
        docker_tag:
          type: string
        enabled:
          format: int32
          type: integer
        frequency:
          type: string
        name:
          type: string
        release_type:
          type: string
        timezone:
          type: string
      type: object
    publisher_upgrade_profile_put_request:
      properties:
        docker_tag:
          type: string
        enabled:
          format: int32
          type: integer
        frequency:
          type: string
        id:
          format: int32
          type: integer
        name:
          type: string
        release_type:
          type: string
        timezone:
          type: string
      type: object
    publisher_upgrade_profile_response:
      properties:
        data:
          properties:
            docker_tag:
              type: string
            enabled:
              format: int32
              type: integer
            frequency:
              type: string
            id:
              format: int32
              type: integer
            name:
              type: string
            release_type:
              type: string
            timezone:
              type: string
          type: object
        status:
          enum:
            - success
            - not found
          type: string
      type: object
    tag_item:
      properties:
        tag_id:
          format: int32
          type: integer
        tag_name:
          type: string
      type: object
info:
  description: NPA publisher upgrade profile CRUD operations.
  title: npa_publisher_upgrade_profile
  version: 1.0.0
openapi: 3.0.0
paths:
  /infrastructure/publisherupgradeprofiles:
    get:
      description: Get list of publisher upgrade profile objects
      parameters:
        - description: Return values only from specified fields
          in: query
          name: fields
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publisher_upgrade_profile_get_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: Get list of publisher upgrade profile objects
    post:
      description: Create a publisher upgrade profile
      parameters:
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/publisher_upgrade_profile_post_request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publisher_upgrade_profile_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: Create a publisher upgrade profile
    x-netskope-params:
      apiGroup: npa_upgrade_profiles
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
  /infrastructure/publisherupgradeprofiles/bulk:
    description: Update the profile of multiple publishers
    put:
      parameters:
        - description:
            "flag to skip output except status code: \n * `1` - Skip response\
            \ data \n * `0` - Do not skip response data"
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/publisher_upgrade_profile_bulk_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publisher_upgrade_profile_bulk_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: "Update the profile of multiple publishers "
    x-netskope-params:
      apiGroup: npa_upgrade_profiles
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
  /infrastructure/publisherupgradeprofiles/{upgrade_profile_id}:
    delete:
      description: Delete a publisher upgrade profile based on profile id
      parameters:
        - description: publisher upgrade profile id
          in: path
          name: upgrade_profile_id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  status:
                    enum:
                      - success
                      - error
                    type: string
                type: object
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: Delete a publisher
    get:
      description:
        get a publisher upgrade profile based on publisher upgrade profile
        id
      parameters:
        - description: publisher upgrade profile id
          in: path
          name: upgrade_profile_id
          required: true
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/publisher_upgrade_profile_response"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: "Get a publisher upgrade profile "
    put:
      description:
        update a publisher upgrade profile based on publisher upgrade profile
        id
      parameters:
        - description: publisher upgrade profile id
          in: path
          name: upgrade_profile_id
          required: true
          schema:
            format: int32
            type: integer
        - description: flag to skip output except status code
          in: query
          name: silent
          required: false
          schema:
            enum:
              - "1"
              - "0"
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/publisher_upgrade_profile_put_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/200"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
          description: Invalid request
      summary: Update a publisher upgrade profile
    x-netskope-params:
      apiGroup: npa_upgrade_profiles
      customerFacing: true
      serviceConfig: provisioner-pycore-ws
      version: 2
