components:
  schemas:
    Appliance:
      properties:
        existed_in_sf_serial_config:
          example: true
          type: boolean
        serial:
          example: FF00000FF0000
          type: string
        tenant_home_pop_name:
          example: US-SJC1
          type: string
        tenant_id:
          example: 14836
          type: integer
        tenant_name:
          example: Netskope Internal Acct
          type: string
      type: object
    CustomLogParser:
      properties:
        parser_content:
          type: object
        parser_name:
          type: string
      required:
        - parser_name
        - parser_content
      type: object
    NotificationConfig:
      properties:
        emails:
          items:
            type: string
          type: array
      required:
        - emails
      type: object
    PiiPrivacyConfig:
      properties:
        enabled:
          type: boolean
        fields_to_protect:
          properties:
            domain:
              type: boolean
            email:
              type: boolean
            from_user:
              type: boolean
            object:
              type: boolean
            page:
              type: boolean
            referer:
              type: boolean
            srcip:
              type: boolean
            to_user:
              type: boolean
            url:
              type: boolean
            user:
              type: boolean
            userip:
              type: boolean
            userkey:
              type: boolean
          type: object
      required:
        - enabled
      type: object
info:
  contact:
    email: eng-risk-insights@netskope.com
    name: Risk Insights
  description: REST APIs exposed by the Log Management Service
  title: Log Management Service
  version: 1.0.0
openapi: 3.0.3
paths:
  /discovery/appliances/{serial}:
    delete:
      description: Delete an appliance for the given serial.
      parameters:
        - example: FF00000FF0000
          in: path
          name: serial
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The serial has been deleted.
        "400":
          description: Bad request.
      summary: Delete an appliance
      tags:
        - Appliance
    get:
      description: Returns a brief appliance info for the given serial.
      parameters:
        - example: FF00000FF0000
          in: path
          name: serial
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Appliance"
          description: successful operation
        "400":
          description: Bad request.
        "404":
          description: Appliance is not found based on the serial number provided.
      summary: Get the appliance
      tags:
        - Appliance
    x-netskope-params:
      apiGroup: logmgmtservice
      customerFacing: true
      serviceConfig: logmgmtservice
      version: 2
  /discovery/customlogparsers:
    get:
      responses:
        "200":
          content:
            application/json:
              examples:
                parsers:
                  value:
                    count: 2
                    result:
                      - parser_content: "..."
                        parser_name: parser_1
                      - parser_content: "..."
                        parser_name: parser_2
              schema:
                properties:
                  count:
                    description: number of custom log parsers
                    type: integer
                  result:
                    items:
                      $ref: "#/components/schemas/CustomLogParser"
                    type: array
          description: list of custom log parsers under this tenant id
        "400":
          description: bad request
        "500":
          description: internal server error
      summary: Get custom log parsers by tenant
      tags:
        - Custom Parser
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomLogParser"
        required: true
      responses:
        "201":
          description: custom log parser created
        "400":
          description: bad request
        "409":
          description: conflict, a parser with this name already exists
        "500":
          description: internal server error
      summary: Create a new custom log parser
      tags:
        - Custom Parser
    x-netskope-params:
      apiGroup: logmgmtservice
      customerFacing: true
      serviceConfig: logmgmtservice
      version: 2
  /discovery/customlogparsers/{name}:
    delete:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: deletion successful
        "400":
          description: bad request
        "500":
          description: internal server error
      summary: Delete a custom log parser
      tags:
        - Custom Parser
    get:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomLogParser"
          description: The desired custom log parser
        "400":
          description: bad request
        "404":
          description: The custom log parser cannot be found
        "500":
          description: internal server error
      summary: Get a custom log parser by tenant ID and parser name
      tags:
        - Custom Parser
    put:
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomLogParser"
        required: true
      responses:
        "202":
          description: update successful
        "400":
          description: bad request
        "409":
          description: parser with this name does not exist
        "500":
          description: internal server error
      summary: Update a custom log parser
      tags:
        - Custom Parser
    x-netskope-params:
      apiGroup: logmgmtservice
      customerFacing: true
      serviceConfig: logmgmtservice
      version: 2
  /discovery/notification:
    get:
      responses:
        "200":
          content:
            application/json:
              examples:
                notification:
                  value:
                    emails:
                      - user1@netskope.com
                      - user2@netskope.com
                      - user3@netskope.com
              schema:
                $ref: "#/components/schemas/NotificationConfig"
          description: the notification config for the given tenant
        "400":
          description: bad request
        "500":
          description: internal server error
      summary: Get the notification configuration for a tenant
      tags:
        - Notification
    put:
      requestBody:
        content:
          application/json:
            examples:
              notification:
                value:
                  emails:
                    - user1@netskope.com
                    - user2@netskope.com
                    - user3@netskope.com
            schema:
              $ref: "#/components/schemas/NotificationConfig"
        required: true
      responses:
        "200":
          description: successful update of the tenant's notification config
        "400":
          description: bad request
        "500":
          description: internal server error
      summary: Update the notification configuration for a tenant
      tags:
        - Notification
    x-netskope-params:
      apiGroup: logmgmtservice
      customerFacing: true
      serviceConfig: logmgmtservice
      version: 2
  /discovery/piiprivacyconfig:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PiiPrivacyConfig"
          description: the pii privacy config for the given tenant
        "400":
          description: bad request
        "404":
          description: pii privacy config does not exist for the given tenant
        "500":
          description: internal server error
      summary: Get the pii privacy config for a tenant
      tags:
        - PII Privacy
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PiiPrivacyConfig"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PiiPrivacyConfig"
          description: the pii privacy config for the given tenant
        "400":
          description: bad request
        "500":
          description: internal server error
      summary: create or replace the pii privacy config for a tenant
      tags:
        - PII Privacy
    x-netskope-params:
      apiGroup: logmgmtservice
      customerFacing: true
      serviceConfig: logmgmtservice
      version: 2
tags:
  - name: Custom Parser
  - name: PII Privacy
  - name: Notification
  - name: Appliance
