info:
  contact:
    email: eng-risk-insights@netskope.com
    name: Risk Insights
  description: REST APIs exposed by the Webuploader Service
  title: Webuploader API
  version: 1.0.0
openapi: 3.0.3
paths:
  /discovery/files/{parsercategory}/{parsertype}:
    post:
      description: Upload a file for log processing.
      parameters:
        - in: path
          name: parsercategory
          required: true
          schema:
            type: string
        - in: path
          name: parsertype
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                filedata:
                  type: string
                filename:
                  type: string
              type: object
          multipart/form-data:
            schema:
              properties:
                files:
                  type: object
              type: object
      responses:
        "200":
          description: Upload successful
        "400":
          description: Invalid request
      summary: Upload a file
    x-netskope-params:
      apiGroup: discovery
      customerFacing: false
      serviceConfig: webuploader
      version: 2
  /discovery/files/{parsercategory}/{parsertype}/{filename}:
    delete:
      description: Delete a file for log processing.
      parameters:
        - in: path
          name: parsercategory
          required: true
          schema:
            type: string
        - in: path
          name: parsertype
          required: true
          schema:
            type: string
        - in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Delete successful
        "400":
          description: Invalid request
      summary: Delete a file
    get:
      description: Get a file for log processing.
      parameters:
        - in: path
          name: parsercategory
          required: true
          schema:
            type: string
        - in: path
          name: parsertype
          required: true
          schema:
            type: string
        - in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  filename:
                    type: string
                  parsercategory:
                    type: string
                  parsertype:
                    type: string
                type: object
          description: The file for log processing
        "400":
          description: Invalid request
        "404":
          description: File not found
      summary: Get a file
    x-netskope-params:
      apiGroup: discovery
      customerFacing: false
      serviceConfig: webuploader
      version: 2
