components:
  schemas:
    BadRequest:
      type: object
      required:
        - code
        - message
        - status
        - request_id
      properties:
        code:
          type: string
        message:
          type: string
        status:
          type: integer
          format: uint16
        request_id:
          type: string
      example:
        code: "400"
        message: Bad Requeset
        request_id: ""
        status: 400
    BadSalesforceGateway:
      type: object
      required:
        - code
        - message
        - status
        - request_id
      properties:
        code:
          type: string
        message:
          type: string
        status:
          type: integer
          format: uint16
        request_id:
          type: string
      example:
        code: bad-gateway
        message: Bad Gateway
        request_id: ""
        status: 502
    Contract:
      type: object
      required:
        - account_id
        - id
        - is_expiring
        - is_expired
        - contract_number
        - start_date
        - end_date
        - expiration_date
        - status
        - contract_term
        - licenses
      properties:
        account_id:
          type: string
        id:
          type: string
        is_expiring:
          type: boolean
        is_expired:
          type: boolean
        contract_number:
          type: string
        start_date:
          type: string
        end_date:
          type: string
        expiration_date:
          type: string
        status:
          type: string
        contract_term:
          type: integer
          format: uint32
        licenses:
          type: array
          items:
            $ref: "#/components/schemas/License"
    GetContractsErrorUnknown:
      type: object
      required:
        - code
        - message
        - status
        - request_id
      properties:
        code:
          type: string
        message:
          type: string
        status:
          type: integer
          format: uint16
        request_id:
          type: string
      example:
        code: server-error
        message: Unknown Server Error
        request_id: ""
        status: 500
    License:
      type: object
      required:
        - id
        - start_date
        - end_date
      properties:
        id:
          type: string
        quantity:
          type: number
          format: double
        product_name:
          type: string
        product_code:
          type: string
        product_description:
          type: string
        quoteline:
          type: string
        start_date:
          type: string
        end_date:
          type: string
info:
  title: polaris-license-api
  version: 0.1.0
openapi: 3.0.0
paths:
  /platform/contracts:
    get:
      responses:
        "200":
          description: ""
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contract"
        "500":
          description: ""
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/GetContractsErrorUnknown"
        "502":
          description: ""
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/BadSalesforceGateway"
        "400":
          description: ""
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/BadRequest"
      operationId: get_contracts
      summary: Get Contracts
      x-netskope-route-params:
    x-netskope-params:
      apiGroup: polaris-license-api
      customerFacing: false
      rateLimit:
        readRoutes:
          second: 4
      serviceConfig: polaris-license-api
      version: 2
