components:
  schemas:
    ASOverlay:
      properties:
        ancillary:
          anyOf:
            - type: boolean
            - type: "null"
          title: Ancillary
        comment:
          anyOf:
            - $ref: "#/components/schemas/Comment"
            - type: "null"
        number:
          title: Number
          type: integer
      required:
        - number
      title: ASOverlay
      type: object
    AbsoluteDate:
      properties:
        absolute:
          format: date-time
          title: Absolute
          type: string
      required:
        - absolute
      title: AbsoluteDate
      type: object
    Comment:
      properties:
        content:
          title: Content
          type: string
        format:
          enum:
            - text
            - markdown
          title: Format
          type: string
      required:
        - format
        - content
      title: Comment
      type: object
    DebugOverlay:
      properties:
        comment:
          anyOf:
            - $ref: "#/components/schemas/Comment"
            - type: "null"
        links:
          anyOf:
            - additionalProperties:
                $ref: "#/components/schemas/DebugTracevizItems"
              type: object
            - type: "null"
          title: Links
        name:
          title: Name
          type: string
        nodes:
          anyOf:
            - additionalProperties:
                $ref: "#/components/schemas/DebugTracevizItems"
              type: object
            - type: "null"
          title: Nodes
        selected:
          title: Selected
          type: boolean
      required:
        - name
        - selected
      title: DebugOverlay
      type: object
    DebugTracevizItems:
      properties:
        comment:
          anyOf:
            - $ref: "#/components/schemas/Comment"
            - type: "null"
        styles:
          items:
            $ref: "#/components/schemas/DebugTracevizStyle"
          title: Styles
          type: array
      required:
        - styles
      title: DebugTracevizItems
      type: object
    DebugTracevizStyle:
      properties:
        color:
          anyOf:
            - type: integer
            - type: string
            - type: "null"
          title: Color
        line:
          anyOf:
            - type: string
            - type: "null"
          title: Line
      title: DebugTracevizStyle
      type: object
    DegradationCauseCheckStatus:
      enum:
        - passed
        - failed
        - unchecked
      title: DegradationCauseCheckStatus
      type: string
    DegradationCauseChecksModel:
      description:
        "Performance field is updated in autopylot/traceroute.py::set_performance_comparison.

        The other fields name are linked to DegradationReason values."
      properties:
        as_routing:
          allOf:
            - $ref: "#/components/schemas/DegradationCauseCheckStatus"
          default: unchecked
        destination:
          allOf:
            - $ref: "#/components/schemas/DegradationCauseCheckStatus"
          default: unchecked
        nodes_degradation:
          allOf:
            - $ref: "#/components/schemas/DegradationCauseCheckStatus"
          default: unchecked
        nodes_routing:
          allOf:
            - $ref: "#/components/schemas/DegradationCauseCheckStatus"
          default: unchecked
        performance:
          allOf:
            - $ref: "#/components/schemas/DegradationCauseCheckStatus"
          default: unchecked
      title: DegradationCauseChecksModel
      type: object
    Diagnostic:
      properties:
        as:
          anyOf:
            - items:
                $ref: "#/components/schemas/ASOverlay"
              type: array
            - type: "null"
          title: As
        checks:
          $ref: "#/components/schemas/DegradationCauseChecksModel"
        explanation:
          anyOf:
            - $ref: "#/components/schemas/Comment"
            - type: "null"
        links:
          anyOf:
            - items:
                $ref: "#/components/schemas/LinksOverlay"
              type: array
            - type: "null"
          title: Links
        methods:
          items:
            type: string
          title: Methods
          type: array
        metric:
          enum:
            - last_rtt
            - loss_h2
          title: Metric
          type: string
        nodes:
          anyOf:
            - items:
                $ref: "#/components/schemas/NodesOverlay"
              type: array
            - type: "null"
          title: Nodes
      required:
        - methods
        - metric
        - checks
      title: Diagnostic
      type: object
    ErrorDict:
      properties:
        ctx:
          title: Ctx
        loc:
          anyOf:
            - items:
                anyOf:
                  - type: string
                  - type: integer
              type: array
            - type: "null"
          title: Loc
        msg:
          title: Msg
          type: string
        type:
          anyOf:
            - type: string
            - type: "null"
          title: Type
      required:
        - msg
      title: ErrorDict
      type: object
    ErrorMessage:
      additionalProperties: false
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ErrorDict"
          title: Detail
          type: array
      required:
        - detail
      title: ErrorMessage
      type: object
    FocusRangeInterval:
      additionalProperties: false
      properties:
        end:
          anyOf:
            - type: number
            - format: date-time
              type: string
          title: End
        metric:
          title: Metric
          type: string
        start:
          anyOf:
            - type: number
            - format: date-time
              type: string
          title: Start
      required:
        - metric
        - start
        - end
      title: FocusRangeInterval
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    LinksOverlay:
      properties:
        ancillary:
          anyOf:
            - type: boolean
            - type: "null"
          title: Ancillary
        comment:
          anyOf:
            - type: string
            - type: "null"
          title: Comment
        from:
          title: From
          type: string
        metrics:
          anyOf:
            - additionalProperties:
                $ref: "#/components/schemas/OneMetricDict"
              type: object
            - type: "null"
          title: Metrics
        to:
          title: To
          type: string
      required:
        - from
        - to
      title: LinksOverlay
      type: object
    NodesOverlay:
      properties:
        ancillary:
          anyOf:
            - type: boolean
            - type: "null"
          title: Ancillary
        comment:
          anyOf:
            - $ref: "#/components/schemas/Comment"
            - type: "null"
        ip:
          title: Ip
          type: string
        metrics:
          anyOf:
            - additionalProperties:
                $ref: "#/components/schemas/OneMetricDict"
              type: object
            - type: "null"
          title: Metrics
      required:
        - ip
      title: NodesOverlay
      type: object
    OneMetricDict:
      properties:
        degraded:
          anyOf:
            - type: number
            - type: "null"
          title: Degraded
        overall:
          title: Overall
          type: number
        unaffected:
          anyOf:
            - type: number
            - type: "null"
          title: Unaffected
      required:
        - overall
      title: OneMetricDict
      type: object
    Options:
      properties:
        sampling:
          default: true
          title: Sampling
          type: boolean
      title: Options
      type: object
    Overlay:
      properties:
        dev:
          anyOf:
            - items:
                $ref: "#/components/schemas/DebugOverlay"
              type: array
            - type: "null"
          title: Dev
        diagnostics:
          items:
            $ref: "#/components/schemas/Diagnostic"
          title: Diagnostics
          type: array
      required:
        - diagnostics
      title: Overlay
      type: object
    RelativeDate:
      properties:
        relative:
          format: date-time
          title: Relative
          type: string
      required:
        - relative
      title: RelativeDate
      type: object
    TraceRouteInput:
      properties:
        begin:
          anyOf:
            - $ref: "#/components/schemas/AbsoluteDate"
            - $ref: "#/components/schemas/RelativeDate"
            - type: "null"
          title: Begin
        diag_metrics:
          default:
            - last_rtt
            - loss_h2
          items:
            enum:
              - last_rtt
              - loss_h2
            type: string
          title: Diag Metrics
          type: array
        end:
          anyOf:
            - $ref: "#/components/schemas/AbsoluteDate"
            - $ref: "#/components/schemas/RelativeDate"
            - type: "null"
          title: End
        focus_on:
          items:
            $ref: "#/components/schemas/FocusRangeInterval"
          title: Focus On
          type: array
        from:
          default: traceroute
          enum:
            - traceroute
            - traceroute_pop
          title: Standard traceroute or traceroute to pops
          type: string
        options:
          allOf:
            - $ref: "#/components/schemas/Options"
          default:
            sampling: true
        orderby:
          items:
            maxItems: 2
            minItems: 2
            prefixItems:
              - type: string
              - enum:
                  - asc
                  - desc
                type: string
            type: array
          title: Orderby
          type: array
        remove_outliers:
          default: false
          title: Remove Outliers
          type: boolean
        where:
          anyOf:
            - items: {}
              type: array
            - type: "null"
          title: Where
      title: TraceRouteInput
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
        - loc
        - msg
        - type
      title: ValidationError
      type: object
    tracerouteCheckModel:
      properties:
        explanation:
          title: Explanation
          type: string
        meta:
          title: Meta
          type: object
        supported:
          title: Supported
          type: boolean
      required:
        - supported
        - explanation
        - meta
      title: tracerouteCheckModel
      type: object
info:
  description: "

    Method Not Allowed

    ------------------


    The status *405 Method Not Allowed* is returned when the requested endpoint exists

    but the Method (GET, PUT, POST...) does not match anything.

    "
  title: Kadiska Data ai API
  version: v1
openapi: 3.1.0
paths:
  /dem/ai/traceroute/checkprerequisites:
    post:
      operationId: traceroute_check_api_v1_ai_traceroute_checkprerequisites_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TraceRouteInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tracerouteCheckModel"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Too many requests (quota exceeded)
      summary: Validate query
      tags:
        - Autopylot
    x-netskope-params:
      apiGroup: dem-workbench-ai
      customerFacing: true
      nsBeta: true
      serviceConfig: dem-workbench-ai
      version: 2
  /dem/ai/traceroute/getclusters:
    post:
      operationId: traceroute_api_v1_ai_traceroute_getclusters_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TraceRouteInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Overlay"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
        "429":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Too many requests (quota exceeded)
      summary: Clusterize Traceroute Graphs
      tags:
        - Autopylot
    x-netskope-params:
      apiGroup: dem-workbench-ai
      customerFacing: true
      nsBeta: true
      serviceConfig: dem-workbench-ai
      version: 2
