components:
  schemas:
    Meta:
      properties:
        location:
          example: https://<account>-goskope.com/scim/ResourceTypes/User
          type: string
        resourceType:
          example: ResourceType
          type: string
      type: object
    ResourceType:
      properties:
        description:
          example: User Account
          type: string
        endpoint:
          example: /Users
          type: string
        id:
          example: User
          type: string
        meta:
          $ref: "#/components/schemas/Meta"
        name:
          example: User
          type: string
        schema:
          example: urn:ietf:params:scim:schemas:core:2.0:User
          type: string
        schemaExtensions:
          example:
            - required: false
              schema: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
            - required: false
              schema: urn:ietf:params:scim:schemas:extension:tenant:2.0:User
            - required: false
              schema: urn:ietf:params:scim:schemas:extension:netskope:2.0:User
          items:
            properties:
              required:
                type: boolean
              schema:
                example: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
                type: string
            type: object
          type: array
        schemas:
          example:
            - urn:ietf:params:scim:schemas:core:2.0:ResourceType
          items:
            properties:
              "0":
                example: urn:ietf:params:scim:schemas:core:2.0:ResourceType
                type: string
            type: object
          type: array
      type: object
    ResourceTypes:
      properties:
        Resources:
          example:
            - description: https://tools.ietf.org/html/rfc7643#section-8.7.1
              endpoint: /Users
              id: User
              meta:
                location: https://<account>-goskope.com/scim/ResourceTypes/User
                resourceType: ResourceType
              name: User
              schema: urn:ietf:params:scim:schemas:core:2.0:User
              schemaExtensions:
                - required: false
                  schema: urn:ietf:params:scim:schemas:extension:enterprise:2.0:User
                - required: false
                  schema: urn:ietf:params:scim:schemas:extension:tenant:2.0:User
                - required: false
                  schema: urn:ietf:params:scim:schemas:extension:netskope:2.0:User
              schemas:
                - urn:ietf:params:scim:schemas:core:2.0:ResourceType
            - description: https://tools.ietf.org/html/rfc7643#section-8.7.1
              endpoint: /Groups
              id: Group
              meta:
                location: https://<account>-goskope.com/scim/ResourceTypes/Group
                resourceType: ResourceType
              name: Group
              schema: urn:ietf:params:scim:schemas:core:2.0:Group
              schemas:
                - urn:ietf:params:scim:schemas:core:2.0:ResourceType
          items:
            $ref: "#/components/schemas/ResourceType"
          type: array
        itemsPerPage:
          example: 2
          type: number
        schemas:
          example:
            - urn:ietf:params:scim:api:messages:2.0:ListResponse
          items:
            properties:
              "0":
                example: urn:ietf:params:scim:api:messages:2.0:ListResponse
                type: string
            type: object
          type: array
        startIndex:
          example: 1
          type: number
        totalResults:
          example: 2
          type: number
      type: object
externalDocs:
  description: SCIM specification
  url: https://www.rfc-editor.org/rfc/rfc7643
info:
  contact:
    email: eng-provisioner-dev-blr@netskope.com
    name: Provisioner
  description: ""
  title: SCIM Custom Attribute API
  version: 2.0.0
openapi: 3.0.0
paths:
  /scim/ResourceTypes:
    get:
      description: Returns list of Resource Types
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceTypes"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Invalid request
                    type: string
                  status:
                    example: "400"
                    type: string
                type: object
          description: Invalid request
        "501":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Internal server error.
                    type: string
                  status:
                    example: 501/failed
                    type: string
                type: object
          description: Internal error Failed
      summary: List Resoure Types
      tags:
        - Resource Types
    x-netskope-params:
      apiGroup: resource-types
      customerFacing: false
      serviceConfig: nsscimserver
      version: 2
  /scim/ResourceTypes/{name}:
    get:
      description: Returns a single Resource Type
      parameters:
        - description: name of Resoure to return
          in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceType"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Invalid request
                    type: string
                  status:
                    example: "400"
                    type: string
                type: object
          description: Invalid request
        "404":
          description: Resource Type not found
        "501":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Internal server error.
                    type: string
                  status:
                    example: 501/failed
                    type: string
                type: object
          description: Internal error Failed
      summary: Find Resource Type by name
      tags:
        - Resource Types
    x-netskope-params:
      apiGroup: resource-types
      customerFacing: false
      serviceConfig: nsscimserver
      version: 2
tags:
  - description: Retrieve the types of resources available on a SCIM service provider
    name: Resource Types
