components:
  schemas:
    Meta:
      properties:
        created:
          example: "2010-01-23T04:56:22.000Z"
          format: date-time
          type: string
        lastModified:
          example: "2011-05-13T04:42:34.000Z"
          format: date-time
          type: string
        location:
          example: https://<account>-goskope.com/scim/ServiceProviderConfig
          type: string
        resourceType:
          example: ServiceProviderConfig
          type: string
      type: object
    ServiceProviderConfig:
      properties:
        authenticationSchemes:
          example:
            - description: Authentication scheme using the OAuth Bearer Token Standard
              documentationUri: http://<account>-goskope.com/help/oauth.html
              name: OAuth Bearer Token
              primary: true
              specUri: http://www.rfc-editor.org/info/rfc6750
              type: oauthbearertoken
            - description: Authentication scheme using the HTTP Basic Standard
              documentationUri: http://<account>-goskope.com/help/httpBasic.html
              name: HTTP Basic
              specUri: http://www.rfc-editor.org/info/rfc2617
              type: httpbasic
          items:
            properties:
              description:
                example: Authentication scheme using the OAuth Bearer Token Standard
                type: string
              documentationUri:
                example: http://<account>-goskope.com/help/oauth.html
                type: string
              name:
                example: OAuth Bearer Token
                type: string
              primary:
                type: boolean
              specUri:
                example: http://www.rfc-editor.org/info/rfc6750
                type: string
              type:
                example: oauthbearertoken
                type: string
            type: object
          type: array
        bulk:
          properties:
            maxOperations:
              example: 1000
              type: number
            maxPayloadSize:
              example: 1048576
              type: number
            supported:
              type: boolean
          type: object
        changePassword:
          properties:
            supported:
              type: boolean
          type: object
        documentationUri:
          example: http://<account>-goskope.com/help/scim.html
          type: string
        etag:
          properties:
            supported:
              type: boolean
          type: object
        filter:
          properties:
            maxResults:
              example: 200
              type: number
            supported:
              type: boolean
          type: object
        meta:
          $ref: "#/components/schemas/Meta"
        patch:
          properties:
            supported:
              type: boolean
          type: object
        schemas:
          example:
            - urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig
          items:
            properties:
              "0":
                example: urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig
                type: string
            type: object
          type: array
        sort:
          properties:
            supported:
              type: boolean
          type: object
      type: object
externalDocs:
  description: SCIM specification
  url: https://www.rfc-editor.org/rfc/rfc7643
info:
  contact:
    email: eng-provisioner-dev-blr@netskope.com
    name: Provisioner
  description: ""
  title: SCIM ServiceProviderConfig API
  version: 2.0.0
openapi: 3.0.0
paths:
  /scim/ServiceProviderConfig:
    get:
      description: Retrieve SCIM specification features available on a service provider
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceProviderConfig"
          description: successful operation
        "400":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Invalid request
                    type: string
                  status:
                    example: "400"
                    type: string
                type: object
          description: Invalid request
        "501":
          content:
            application/json:
              schema:
                properties:
                  description:
                    example: Internal server error.
                    type: string
                  status:
                    example: 501/failed
                    type: string
                type: object
          description: Internal error Failed
      summary: Service Provider Config
      tags:
        - Service Provider Config
    x-netskope-params:
      apiGroup: service-provider-config
      customerFacing: false
      serviceConfig: nsscimserver
      version: 2
tags:
  - description: Retrieve SCIM specification features available on a service provider
    name: Service Provider Config
