components: {}
info:
  contact:
    name: ""
  description: ""
  title: ms-auth
  version: 1.0.0
openapi: 3.0.3
paths:
  /ui/auth/authorize/pagepermissions:
    get:
      description: Replies with highest permission
      parameters:
        - in: query
          name: parentpagename
          required: true
          schema:
            description: Parent page full name
            type: string
        - in: query
          name: pagename
          required: true
          schema:
            description: Parent page full name
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: rw
                  msg: Success message
                  success: true
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                example:
                  data: null
                  msg: Unauthorized error message
                  success: false
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: User error response
        4XX:
          content:
            application/json:
              schema:
                example:
                  data: null
                  msg: User error message
                  success: false
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: User error response
        "500":
          content:
            application/json:
              schema:
                example:
                  data: null
                  msg: Error message
                  success: false
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Unexpected error.
      summary: Replies with highest permission
    x-netskope-params:
      apiGroup: ms-auth
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-auth
      version: 2
tags: []
